import { expect, test } from '@playwright/test';

test('real question forms create, edit, preview, unsaved changes and concurrency', async ({ page, request, browser }) => {
  const api = process.env.ADMIN_E2E_API_URL!; const packageResponse = await request.post(`${api}/api/admin/content-packages`, { data: { namePl: 'E2E formularze', nameEn: 'E2E forms' } }); expect(packageResponse.ok()).toBeTruthy(); const pkg = await packageResponse.json();
  let token = pkg.concurrencyToken; const addCategory = async (key: string, name: string) => { const response = await request.post(`${api}/api/admin/content-packages/${pkg.id}/categories`, { data: { key, namePl: name, nameEn: name, packageConcurrencyToken: token } }); expect(response.ok()).toBeTruthy(); const body = await response.json(); token = body.packageConcurrencyToken; return body.category; };
  const first = await addCategory('forms_one', 'Formularze 1'); const secondCategory = await addCategory('forms_two', 'Formularze 2'); const helper = await request.post(`${api}/api/admin/content-packages/${pkg.id}/questions`, { data: { categoryId: secondCategory.id, key: 'second_helper', type: 'TextAnswer', textPl: 'Pomocnicze', textEn: 'Helper', minimumPlayers: 3 } }); expect(helper.ok()).toBeTruthy();
  await page.goto(`/admin/content/packages/${pkg.id}/questions/new?page=2&categoryId=${first.id}`); await page.getByRole('button', { name: 'Zapisz' }).click(); await expect(page.getByText('Key jest wymagany.')).toBeVisible(); await page.getByLabel('Key').fill('player_question'); await page.getByLabel('Tekst PL').fill('Wybierz {player}'); await page.getByLabel('Tekst EN').fill('Choose {player}'); await expect(page.getByLabel('Podgląd pytania')).toContainText('Wybierz {player}'); await page.getByRole('button', { name: 'Zapisz' }).click(); await expect(page.getByText('Edycja pytania')).toBeVisible();
  await page.getByLabel('Typ pytania').selectOption('TextAnswer'); await expect(page.getByLabel('Podgląd pytania')).toContainText('Gracze wpisują własną odpowiedź tekstową.'); await page.getByLabel('Tekst PL').fill('Tekst po zmianie'); await page.getByRole('button', { name: 'Zapisz' }).click();
  await page.getByLabel('Typ pytania').selectOption('PhotoAnswer'); await expect(page.getByLabel('Podgląd pytania')).toContainText('Dodaj zdjęcie'); await page.getByLabel('Typ pytania').selectOption('DrawingAnswer'); await expect(page.getByLabel('Podgląd pytania')).toContainText('Płótno rysunku'); await page.getByLabel('Tekst PL').fill('<script>alert(1)</script>'); await expect(page.getByLabel('Podgląd pytania')).toContainText('<script>alert(1)</script>'); await expect(page.getByLabel('Podgląd pytania').locator('script')).toHaveCount(0);
  await page.getByRole('button', { name: 'Wróć do listy' }).click(); await expect(page.getByRole('dialog')).toBeVisible(); await page.getByRole('button', { name: 'Zostań' }).click(); await page.getByRole('button', { name: 'Wróć do listy' }).click(); await page.getByRole('button', { name: 'Opuść bez zapisywania' }).click(); await expect(page).toHaveURL(new RegExp(`questions\\?page=2`));
  const list = await (await request.get(`${api}/api/admin/content-packages/${pkg.id}/questions`)).json(); const question = list.items[0]; const second = await browser.newContext(); const pageB = await second.newPage(); await page.goto(`/admin/content/packages/${pkg.id}/questions/${question.id}`); await pageB.goto(`/admin/content/packages/${pkg.id}/questions/${question.id}`); await pageB.getByLabel('Tekst PL').fill('Zapis B'); await pageB.getByRole('button', { name: 'Zapisz' }).click(); await page.getByLabel('Tekst PL').fill('Zapis A'); await page.getByRole('button', { name: 'Zapisz' }).click(); await expect(page.getByRole('alert')).toContainText('zmienione w innej sesji'); await page.getByRole('button', { name: 'Odśwież dane' }).click(); await expect(page.getByLabel('Tekst PL')).toHaveValue('Zapis B'); await second.close();
  const fresh = await (await request.get(`${api}/api/admin/content-packages/${pkg.id}`)).json(); const publish = await request.post(`${api}/api/admin/content-packages/${pkg.id}/publish`, { data: { concurrencyToken: fresh.concurrencyToken } }); expect(publish.ok()).toBeTruthy(); await page.reload(); await expect(page.getByText(/tylko do odczytu/)).toBeVisible(); await expect(page.getByRole('button', { name: 'Zapisz' })).toHaveCount(0);
});
