import { useMemo, useState } from 'react';
import { publicMediaUrl } from '../../api/roomApi';
import { gameCategory, gameQuestion, localizedText, type AnonymousDrawingOption, type DrawingAnswerResultOption, type GameSnapshot, type RoomSnapshot } from '../../api/types';
import { useTimer } from './useTimer';

function url(path?: string | null) { return publicMediaUrl(path); }
function Header({ game }: { game: GameSnapshot }) { const seconds = useTimer(game.stageEndsAtUtc); return <header className="photo-stage-header"><p>Runda {game.currentRoundNumber} · Pytanie {game.currentQuestionNumber}/{game.questionsInCurrentRound}</p><p>{localizedText(gameCategory(game)?.name)}</p><h1>{localizedText(gameQuestion(game)?.text)}</h1><strong>{seconds}s</strong></header>; }
function DrawingImage({ src, alt }: { src?: string | null; alt: string }) {
  const [failed, setFailed] = useState(false);
  if (!src || failed) return <div className="photo-fallback" role="img" aria-label={`${alt}. Rysunek niedostępny`} data-testid="drawing-answer-image">✏️</div>;
  return <img className="photo-answer-image" src={url(src)} alt={alt} onError={() => setFailed(true)} data-testid="drawing-answer-image" />;
}
function ordered(options: AnonymousDrawingOption[]) { return [...options].sort((a, b) => (a.displayOrder ?? a.revealOrder ?? 0) - (b.displayOrder ?? b.revealOrder ?? 0)); }

export function CollectingDrawingAnswersView({ game, room }: { game: GameSnapshot; room: RoomSnapshot }) { const data = game.drawingAnswerResults; return <section className="photo-stage" data-testid="drawing-collecting"><Header game={game} /><p>{data?.submittedPlayers ?? data?.submittedDrawingAnswers ?? 0} z {data?.requiredPlayers ?? data?.requiredDrawingAnswers ?? room.players.length} graczy przesłało rysunek</p><p>Czekamy na rysunki z telefonów…</p></section>; }
export function RevealingDrawingAnswersView({ game }: { game: GameSnapshot }) { const options = ordered(game.drawingAnswerResults?.anonymousOptions ?? []); return <section className="photo-stage" data-testid="revealing-drawing-answers"><Header game={game} />{options.length === 0 ? <Empty /> : <div className="photo-gallery photo-gallery--reveal">{options.map((option, index) => <article className="photo-card anonymous" key={option.drawingAnswerId}><DrawingImage src={option.displayDrawingUrl} alt={`Rysunek numer ${index + 1}`} /><span>Rysunek {index + 1}</span></article>)}</div>}</section>; }
export function CollectingDrawingAnswerVotesView({ game }: { game: GameSnapshot }) { const data = game.drawingAnswerResults; return <section className="photo-stage" data-testid="collecting-drawing-answer-votes"><Header game={game} /><p>Zagłosowało {data?.votedPlayers ?? 0} z {data?.requiredVoters ?? 0}</p><p>Głosujcie na telefonach</p><div className="photo-gallery">{ordered(data?.anonymousOptions ?? []).map((option, index) => <article className="photo-card anonymous" key={option.drawingAnswerId}><DrawingImage src={option.thumbnailDrawingUrl} alt={`Rysunek numer ${index + 1}`} /></article>)}</div></section>; }
function Result({ option, index }: { option: DrawingAnswerResultOption; index: number }) { return <article className={`photo-result-card ${option.isTopResult ? 'top-result' : ''}`}>{option.isTopResult && <strong className="winner-badge">Najwięcej głosów</strong>}<DrawingImage src={option.displayDrawingUrl} alt={`Rysunek ${index + 1}, autor ${option.authorNickname}`} /><p data-testid="drawing-author"><strong>Autor rysunku: {option.authorNickname}</strong></p><p data-testid="drawing-votes">{option.voteCount} głosów</p>{option.voters.length > 0 && <div><h3>Głosowali</h3>{option.voters.map(voter => <p key={voter.playerId}>{voter.nickname} <strong data-testid="drawing-points">+{voter.pointsAwarded} pkt</strong></p>)}</div>}</article>; }
export function ShowingDrawingAnswerResultsView({ game }: { game: GameSnapshot }) { const options = useMemo(() => game.drawingAnswerResults?.options ?? [], [game.drawingAnswerResults?.options]); return <section className="photo-stage" data-testid="showing-drawing-answer-results"><Header game={game} />{options.length === 0 ? <Empty /> : <div className="photo-results-grid">{options.map((option, index) => <Result option={option} index={index} key={option.drawingAnswerId} />)}</div>}</section>; }
function Empty() { return <div className="photo-empty" role="status"><span>✏️</span><h2>Nikt nie przesłał rysunku</h2></div>; }
