import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import { describe, expect, it } from 'vitest';
import type { GameSnapshot, RoomSnapshot } from '../../api/types';
import { configureApiConfig } from '../../api/apiConfig';
import { GameScreens } from './GameScreens';

const game: GameSnapshot = { stage: 'CollectingDrawingAnswers', currentRoundNumber: 1, totalRounds: 1, currentQuestionNumber: 1, questionsInCurrentRound: 4, scores: [], currentQuestion: { id: 'q1', text: 'Narysuj kota' }, drawingAnswerResults: { questionInstanceId: 'q1', submittedDrawingAnswers: 1, requiredDrawingAnswers: 3, anonymousOptions: [{ drawingAnswerId: 'd1', displayDrawingUrl: '/display', thumbnailDrawingUrl: '/thumb', revealOrder: 0, displayOrder: 0, width: 1024, height: 1024 }] } };
const room: RoomSnapshot = { roomCode: 'ABCD', phase: 'Started', stateVersion: 1, displayConnected: true, minimumPlayers: 3, maximumPlayers: 8, canStart: false, settings: {} as RoomSnapshot['settings'], players: [], createdAtUtc: '', game };

describe('DrawingAnswer Display', () => {
  it('resolves public drawing media through the configured API path prefix', () => { configureApiConfig({ apiBaseUrl: '/partygame', publicAppUrl: '/partygame/display', buildVersion: 'test' }); render(<GameScreens snapshot={{ ...room, game: { ...game, stage: 'RevealingDrawingAnswers' } }} />); expect(screen.getByTestId('drawing-answer-image')).toHaveAttribute('src', '/partygame/display'); });
  it('collecting exposes progress but no image', () => { render(<GameScreens snapshot={room} />); expect(screen.getByText('1 z 3 graczy przesłało rysunek')).toBeInTheDocument(); expect(screen.queryByRole('img')).not.toBeInTheDocument(); });
  it('reveal and voting remain anonymous', () => { const { rerender } = render(<GameScreens snapshot={{ ...room, game: { ...game, stage: 'RevealingDrawingAnswers' } }} />); expect(screen.getByText('Rysunek 1')).toBeInTheDocument(); expect(screen.queryByText('Ola')).not.toBeInTheDocument(); rerender(<GameScreens snapshot={{ ...room, game: { ...game, stage: 'CollectingDrawingAnswerVotes', drawingAnswerResults: { ...game.drawingAnswerResults!, votedPlayers: 1, requiredVoters: 3 } } }} />); expect(screen.getByText('Zagłosowało 1 z 3')).toBeInTheDocument(); });
  it('results reveal authors, voters, ties and empty state', () => { const result = { drawingAnswerId: 'd1', displayDrawingUrl: '/display', thumbnailDrawingUrl: '/thumb', width: 1024, height: 1024, authorPlayerId: 'p1', authorNickname: 'Ola', voteCount: 2, isTopResult: true, voters: [{ playerId: 'p2', nickname: 'Jan', pointsAwarded: 200 }] }; const { rerender } = render(<GameScreens snapshot={{ ...room, game: { ...game, stage: 'ShowingDrawingAnswerResults', drawingAnswerResults: { ...game.drawingAnswerResults!, options: [result] } } }} />); expect(screen.getByText(/Autor rysunku/)).toHaveTextContent('Ola'); expect(screen.getByText('+200 pkt')).toBeInTheDocument(); rerender(<GameScreens snapshot={{ ...room, game: { ...game, stage: 'ShowingDrawingAnswerResults', drawingAnswerResults: { ...game.drawingAnswerResults!, options: [] } } }} />); expect(screen.getByText('Nikt nie przesłał rysunku')).toBeInTheDocument(); });
});
