// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartyGame.Infrastructure.Persistence;

#nullable disable

namespace PartyGame.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PartyGameDbContext))]
    [Migration("20260720160809_AddLobbyRooms")]
    partial class AddLobbyRooms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PartyGame.Domain.Rooms.GameRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisplayConnected")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("HostPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("StateVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GameRooms", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasProfilePhoto")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHost")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReady")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedNickname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("ProfilePhotoContentType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePhotoStorageKey")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "NormalizedNickname")
                        .IsUnique();

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.PlayerSession", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReconnectTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerSessions", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.RoomSettings", b =>
                {
                    b.Property<Guid>("GameRoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrawingSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FinalDrawingPasses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FinalRoundEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhotoSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerSelectionSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionsPerRound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResultPresentationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TextAnswerSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VotingSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameRoomId");

                    b.ToTable("RoomSettings", (string)null);
                });

            modelBuilder.Entity("PartyGame.Infrastructure.Persistence.DatabaseMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DatabaseMetadata", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.Player", b =>
                {
                    b.HasOne("PartyGame.Domain.Rooms.GameRoom", "Room")
                        .WithMany("Players")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.PlayerSession", b =>
                {
                    b.HasOne("PartyGame.Domain.Rooms.Player", "Player")
                        .WithOne("Session")
                        .HasForeignKey("PartyGame.Domain.Rooms.PlayerSession", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.RoomSettings", b =>
                {
                    b.HasOne("PartyGame.Domain.Rooms.GameRoom", null)
                        .WithOne("Settings")
                        .HasForeignKey("PartyGame.Domain.Rooms.RoomSettings", "GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.GameRoom", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.Player", b =>
                {
                    b.Navigation("Session")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
