// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartyGame.Infrastructure.Persistence;

#nullable disable

namespace PartyGame.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PartyGameDbContext))]
    [Migration("20260721191126_Stage5ACompletionFix")]
    partial class Stage5ACompletionFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PartyGame.Domain.Content.GameCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionPl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("PackageId");

                    b.ToTable("GameCategories", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Content.GamePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionPl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("GamePackages", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Content.GameQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextPl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("GameQuestions", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.DrawingAnswerEligiblePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("QuestionInstanceId", "PlayerId")
                        .IsUnique();

                    b.ToTable("DrawingAnswerEligiblePlayers", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.DrawingAnswerSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientSubmissionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RevealOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorPlayerId");

                    b.HasIndex("MediaAssetId")
                        .IsUnique();

                    b.HasIndex("QuestionInstanceId", "AuthorPlayerId")
                        .IsUnique();

                    b.HasIndex("QuestionInstanceId", "ClientSubmissionId")
                        .IsUnique();

                    b.HasIndex("QuestionInstanceId", "RevealOrder")
                        .IsUnique();

                    b.ToTable("DrawingAnswerSubmissions", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.DrawingAnswerVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SelectedDrawingAnswerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VoterPlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SelectedDrawingAnswerId");

                    b.HasIndex("VoterPlayerId");

                    b.HasIndex("QuestionInstanceId", "VoterPlayerId")
                        .IsUnique();

                    b.ToTable("DrawingAnswerVotes", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.DrawingAnswerVoteEligiblePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("QuestionInstanceId", "PlayerId")
                        .IsUnique();

                    b.ToTable("DrawingAnswerVoteEligiblePlayers", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.GameQuestionEligiblePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("QuestionInstanceId", "PlayerId")
                        .IsUnique();

                    b.ToTable("GameQuestionEligiblePlayers", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.GameQuestionInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AnsweringEndsAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AnsweringStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ResultsStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubjectPlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("RoundId");

                    b.ToTable("GameQuestionInstances", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.GameRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GameSessionId");

                    b.ToTable("GameRounds", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentQuestionInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentQuestionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentRoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("PausedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PausedRemainingMilliseconds")
                        .HasColumnType("REAL");

                    b.Property<int?>("PausedStage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionsInCurrentRound")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StageEndsAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StageStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("GameSessions", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayStorageKey")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailStorageKey")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MediaAssets", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.PhotoAnswerEligiblePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("QuestionInstanceId", "PlayerId")
                        .IsUnique();

                    b.ToTable("PhotoAnswerEligiblePlayers", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.PhotoAnswerSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientSubmissionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RevealOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorPlayerId");

                    b.HasIndex("MediaAssetId")
                        .IsUnique();

                    b.HasIndex("QuestionInstanceId", "AuthorPlayerId")
                        .IsUnique();

                    b.HasIndex("QuestionInstanceId", "ClientSubmissionId")
                        .IsUnique();

                    b.HasIndex("QuestionInstanceId", "RevealOrder")
                        .IsUnique();

                    b.ToTable("PhotoAnswerSubmissions", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.PhotoAnswerVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SelectedPhotoAnswerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VoterPlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SelectedPhotoAnswerId");

                    b.HasIndex("VoterPlayerId");

                    b.HasIndex("QuestionInstanceId", "VoterPlayerId")
                        .IsUnique();

                    b.ToTable("PhotoAnswerVotes", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.PhotoAnswerVoteEligiblePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("QuestionInstanceId", "PlayerId")
                        .IsUnique();

                    b.ToTable("PhotoAnswerVoteEligiblePlayers", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.PlayerSelectionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PointsAwarded")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuestionInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SelectedPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VoterPlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SelectedPlayerId");

                    b.HasIndex("VoterPlayerId");

                    b.HasIndex("QuestionInstanceId", "VoterPlayerId")
                        .IsUnique();

                    b.ToTable("PlayerSelectionAnswers", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.ScoreTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuestionInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("QuestionInstanceId", "PlayerId")
                        .IsUnique();

                    b.ToTable("ScoreTransactions", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.TextAnswerEligiblePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionInstanceId", "PlayerId")
                        .IsUnique();

                    b.ToTable("TextAnswerEligiblePlayers", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.TextAnswerSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RevealOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionInstanceId", "AuthorPlayerId")
                        .IsUnique();

                    b.HasIndex("QuestionInstanceId", "RevealOrder")
                        .IsUnique();

                    b.ToTable("TextAnswerSubmissions", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.TextAnswerVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SelectedTextAnswerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VoterPlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionInstanceId", "VoterPlayerId")
                        .IsUnique();

                    b.ToTable("TextAnswerVotes", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Game.TextAnswerVoteEligiblePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionInstanceId", "PlayerId")
                        .IsUnique();

                    b.ToTable("TextAnswerVoteEligiblePlayers", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.GameRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisplayConnected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnabledQuestionTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HostPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedPackageKeys")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("StateVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GameRooms", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasProfilePhoto")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHost")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReady")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedNickname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("ProfilePhotoContentType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePhotoStorageKey")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "NormalizedNickname")
                        .IsUnique();

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.PlayerSession", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReconnectTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerSessions", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.RoomSettings", b =>
                {
                    b.Property<Guid>("GameRoomId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrawingSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FinalDrawingPasses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FinalRoundEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhotoSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerSelectionSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionsPerRound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResultPresentationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TextAnswerSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VotingSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameRoomId");

                    b.ToTable("RoomSettings", (string)null);
                });

            modelBuilder.Entity("PartyGame.Infrastructure.Persistence.DatabaseMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DatabaseMetadata", (string)null);
                });

            modelBuilder.Entity("PartyGame.Domain.Content.GameCategory", b =>
                {
                    b.HasOne("PartyGame.Domain.Content.GamePackage", "Package")
                        .WithMany("Categories")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PartyGame.Domain.Content.GameQuestion", b =>
                {
                    b.HasOne("PartyGame.Domain.Content.GameCategory", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PartyGame.Domain.Game.DrawingAnswerEligiblePlayer", b =>
                {
                    b.HasOne("PartyGame.Domain.Rooms.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Game.GameQuestionInstance", null)
                        .WithMany("DrawingAnswerEligiblePlayers")
                        .HasForeignKey("QuestionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGame.Domain.Game.DrawingAnswerSubmission", b =>
                {
                    b.HasOne("PartyGame.Domain.Rooms.Player", null)
                        .WithMany()
                        .HasForeignKey("AuthorPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Game.MediaAsset", "MediaAsset")
                        .WithOne()
                        .HasForeignKey("PartyGame.Domain.Game.DrawingAnswerSubmission", "MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Game.GameQuestionInstance", null)
                        .WithMany("DrawingAnswerSubmissions")
                        .HasForeignKey("QuestionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("PartyGame.Domain.Game.DrawingAnswerVote", b =>
                {
                    b.HasOne("PartyGame.Domain.Game.GameQuestionInstance", null)
                        .WithMany("DrawingAnswerVotes")
                        .HasForeignKey("QuestionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Game.DrawingAnswerSubmission", null)
                        .WithMany()
                        .HasForeignKey("SelectedDrawingAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Rooms.Player", null)
                        .WithMany()
                        .HasForeignKey("VoterPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGame.Domain.Game.DrawingAnswerVoteEligiblePlayer", b =>
                {
                    b.HasOne("PartyGame.Domain.Rooms.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Game.GameQuestionInstance", null)
                        .WithMany("DrawingAnswerVoteEligiblePlayers")
                        .HasForeignKey("QuestionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGame.Domain.Game.GameQuestionEligiblePlayer", b =>
                {
                    b.HasOne("PartyGame.Domain.Rooms.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Game.GameQuestionInstance", "QuestionInstance")
                        .WithMany("EligiblePlayers")
                        .HasForeignKey("QuestionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("QuestionInstance");
                });

            modelBuilder.Entity("PartyGame.Domain.Game.GameQuestionInstance", b =>
                {
                    b.HasOne("PartyGame.Domain.Content.GameQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Game.GameRound", "Round")
                        .WithMany("Questions")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("PartyGame.Domain.Game.GameRound", b =>
                {
                    b.HasOne("PartyGame.Domain.Content.GameCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Game.GameSession", "Session")
                        .WithMany("Rounds")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("PartyGame.Domain.Game.GameSession", b =>
                {
                    b.HasOne("PartyGame.Domain.Rooms.GameRoom", "Room")
                        .WithOne("Session")
                        .HasForeignKey("PartyGame.Domain.Game.GameSession", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PartyGame.Domain.Game.PhotoAnswerEligiblePlayer", b =>
                {
                    b.HasOne("PartyGame.Domain.Rooms.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Game.GameQuestionInstance", null)
                        .WithMany("PhotoAnswerEligiblePlayers")
                        .HasForeignKey("QuestionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGame.Domain.Game.PhotoAnswerSubmission", b =>
                {
                    b.HasOne("PartyGame.Domain.Rooms.Player", null)
                        .WithMany()
                        .HasForeignKey("AuthorPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Game.MediaAsset", "MediaAsset")
                        .WithOne()
                        .HasForeignKey("PartyGame.Domain.Game.PhotoAnswerSubmission", "MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Game.GameQuestionInstance", null)
                        .WithMany("PhotoAnswerSubmissions")
                        .HasForeignKey("QuestionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("PartyGame.Domain.Game.PhotoAnswerVote", b =>
                {
                    b.HasOne("PartyGame.Domain.Game.GameQuestionInstance", null)
                        .WithMany("PhotoAnswerVotes")
                        .HasForeignKey("QuestionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Game.PhotoAnswerSubmission", null)
                        .WithMany()
                        .HasForeignKey("SelectedPhotoAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Rooms.Player", null)
                        .WithMany()
                        .HasForeignKey("VoterPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGame.Domain.Game.PhotoAnswerVoteEligiblePlayer", b =>
                {
                    b.HasOne("PartyGame.Domain.Rooms.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Game.GameQuestionInstance", null)
                        .WithMany("PhotoAnswerVoteEligiblePlayers")
                        .HasForeignKey("QuestionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGame.Domain.Game.PlayerSelectionAnswer", b =>
                {
                    b.HasOne("PartyGame.Domain.Game.GameQuestionInstance", "QuestionInstance")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Rooms.Player", "SelectedPlayer")
                        .WithMany()
                        .HasForeignKey("SelectedPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Rooms.Player", "VoterPlayer")
                        .WithMany()
                        .HasForeignKey("VoterPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionInstance");

                    b.Navigation("SelectedPlayer");

                    b.Navigation("VoterPlayer");
                });

            modelBuilder.Entity("PartyGame.Domain.Game.ScoreTransaction", b =>
                {
                    b.HasOne("PartyGame.Domain.Game.GameSession", "Session")
                        .WithMany("ScoreTransactions")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Rooms.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartyGame.Domain.Game.GameQuestionInstance", "QuestionInstance")
                        .WithMany()
                        .HasForeignKey("QuestionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("QuestionInstance");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("PartyGame.Domain.Game.TextAnswerEligiblePlayer", b =>
                {
                    b.HasOne("PartyGame.Domain.Game.GameQuestionInstance", null)
                        .WithMany("TextAnswerEligiblePlayers")
                        .HasForeignKey("QuestionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGame.Domain.Game.TextAnswerSubmission", b =>
                {
                    b.HasOne("PartyGame.Domain.Game.GameQuestionInstance", null)
                        .WithMany("TextAnswerSubmissions")
                        .HasForeignKey("QuestionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGame.Domain.Game.TextAnswerVote", b =>
                {
                    b.HasOne("PartyGame.Domain.Game.GameQuestionInstance", null)
                        .WithMany("TextAnswerVotes")
                        .HasForeignKey("QuestionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGame.Domain.Game.TextAnswerVoteEligiblePlayer", b =>
                {
                    b.HasOne("PartyGame.Domain.Game.GameQuestionInstance", null)
                        .WithMany("TextAnswerVoteEligiblePlayers")
                        .HasForeignKey("QuestionInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.Player", b =>
                {
                    b.HasOne("PartyGame.Domain.Rooms.GameRoom", "Room")
                        .WithMany("Players")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.PlayerSession", b =>
                {
                    b.HasOne("PartyGame.Domain.Rooms.Player", "Player")
                        .WithOne("Session")
                        .HasForeignKey("PartyGame.Domain.Rooms.PlayerSession", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.RoomSettings", b =>
                {
                    b.HasOne("PartyGame.Domain.Rooms.GameRoom", null)
                        .WithOne("Settings")
                        .HasForeignKey("PartyGame.Domain.Rooms.RoomSettings", "GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGame.Domain.Content.GameCategory", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("PartyGame.Domain.Content.GamePackage", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("PartyGame.Domain.Game.GameQuestionInstance", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("DrawingAnswerEligiblePlayers");

                    b.Navigation("DrawingAnswerSubmissions");

                    b.Navigation("DrawingAnswerVoteEligiblePlayers");

                    b.Navigation("DrawingAnswerVotes");

                    b.Navigation("EligiblePlayers");

                    b.Navigation("PhotoAnswerEligiblePlayers");

                    b.Navigation("PhotoAnswerSubmissions");

                    b.Navigation("PhotoAnswerVoteEligiblePlayers");

                    b.Navigation("PhotoAnswerVotes");

                    b.Navigation("TextAnswerEligiblePlayers");

                    b.Navigation("TextAnswerSubmissions");

                    b.Navigation("TextAnswerVoteEligiblePlayers");

                    b.Navigation("TextAnswerVotes");
                });

            modelBuilder.Entity("PartyGame.Domain.Game.GameRound", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("PartyGame.Domain.Game.GameSession", b =>
                {
                    b.Navigation("Rounds");

                    b.Navigation("ScoreTransactions");
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.GameRoom", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Session");

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("PartyGame.Domain.Rooms.Player", b =>
                {
                    b.Navigation("Session")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
