import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { AdminContentApiError, adminContentApi, type Category } from '../../api/adminContentApi';
import { CategoryManager } from './CategoryManager';

vi.mock('../../api/adminContentApi', async (original) => {
  const actual = await original<typeof import('../../api/adminContentApi')>();
  return { ...actual, adminContentApi: { listCategories: vi.fn(), getPackage: vi.fn(), createCategory: vi.fn(), updateCategory: vi.fn(), deleteCategory: vi.fn(), reorderCategories: vi.fn() } };
});
const category: Category = { id: 'c1', packageId: 'p1', key: 'funny', namePl: 'Zabawne', nameEn: 'Funny', descriptionPl: '', descriptionEn: '', isActive: true, sortOrder: 0, questionCount: 0, concurrencyToken: 'ct1' };
const renderPage = () => render(<MemoryRouter initialEntries={['/admin/content/packages/p1/categories']}><Routes><Route path="/admin/content/packages/:packageVersionId/categories" element={<CategoryManager/>}/></Routes></MemoryRouter>);

describe('CategoryManager', () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [category], packageConcurrencyToken: 'pt1' }); vi.mocked(adminContentApi.getPackage).mockResolvedValue({ id: 'p1', logicalPackageId: 'l1', version: 1, key: 'p', namePl: 'P', nameEn: 'P', status: 'Draft', isActive: true, categoryCount: 1, questionCount: 0, concurrencyToken: 'pt1' }); });
  it('pokazuje loading i listę kategorii', async () => { renderPage(); expect(screen.getByText('Wczytywanie kategorii…')).toBeInTheDocument(); expect(await screen.findByText('Zabawne')).toBeInTheDocument(); expect(screen.getAllByText(/Aktywna/).length).toBeGreaterThan(0); });
  it('pokazuje pusty stan', async () => { vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [], packageConcurrencyToken: 'pt1' }); renderPage(); expect(await screen.findByText(/nie ma jeszcze kategorii/)).toBeInTheDocument(); });
  it('tworzy kategorię przez API', async () => { vi.mocked(adminContentApi.createCategory).mockResolvedValue({ category, packageConcurrencyToken: 'pt2' }); renderPage(); await screen.findByText('Zabawne'); await userEvent.clear(screen.getByLabelText('Key')); await userEvent.type(screen.getByLabelText('Key'), 'new'); await userEvent.type(screen.getByLabelText('Nazwa PL'), 'Nowa'); await userEvent.type(screen.getByLabelText('Nazwa EN'), 'New'); await userEvent.click(screen.getByRole('button', { name: 'Zapisz' })); await waitFor(() => expect(adminContentApi.createCategory).toHaveBeenCalled()); });
  it('edytuje i wyłącza kategorię prawdziwym PATCH', async () => { vi.mocked(adminContentApi.updateCategory).mockResolvedValue({ category: { ...category, isActive: false }, packageConcurrencyToken: 'pt2' }); renderPage(); await screen.findByText('Zabawne'); await userEvent.click(screen.getByRole('button', { name: 'Wyłącz' })); await waitFor(() => expect(adminContentApi.updateCategory).toHaveBeenCalledWith('p1', 'c1', expect.objectContaining({ isActive: false, concurrencyToken: 'ct1' }))); });
  it('zachowuje formularz po konflikcie', async () => { vi.mocked(adminContentApi.updateCategory).mockRejectedValue(new AdminContentApiError(409, 'Ta kategoria została zmieniona w innej sesji.')); renderPage(); await screen.findByText('Zabawne'); await userEvent.click(screen.getByRole('button', { name: 'Edytuj' })); await userEvent.clear(screen.getByLabelText('Nazwa PL')); await userEvent.type(screen.getByLabelText('Nazwa PL'), 'Moje dane'); await userEvent.click(screen.getByRole('button', { name: 'Zapisz' })); expect(await screen.findByRole('alert')).toHaveTextContent('zmieniona w innej sesji'); expect(screen.getByLabelText('Nazwa PL')).toHaveValue('Moje dane'); });
  it('ukrywa mutacje dla Published', async () => { vi.mocked(adminContentApi.getPackage).mockResolvedValue({ id: 'p1', logicalPackageId: 'l1', version: 1, key: 'p', namePl: 'P', nameEn: 'P', status: 'Published', isActive: true, categoryCount: 1, questionCount: 0, concurrencyToken: 'pt1' }); renderPage(); expect(await screen.findByText(/tylko do odczytu/)).toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Edytuj' })).not.toBeInTheDocument(); });
  it('renderuje tekst XSS jako plain text', async () => { vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [{ ...category, namePl: '<script>alert(1)</script>' }], packageConcurrencyToken: 'pt1' }); renderPage(); expect(await screen.findByText('<script>alert(1)</script>')).toBeInTheDocument(); });
  it('pokazuje błąd pobrania i retry ładuje dane', async () => { vi.mocked(adminContentApi.listCategories).mockRejectedValueOnce(new Error('Błąd sieci')).mockResolvedValueOnce({ items: [category], packageConcurrencyToken: 'pt1' }); renderPage(); expect(await screen.findByRole('alert')).toHaveTextContent('Błąd sieci'); await userEvent.click(screen.getByRole('button', { name: 'Odśwież dane' })); expect(await screen.findByText('Zabawne')).toBeInTheDocument(); expect(adminContentApi.listCategories).toHaveBeenCalledTimes(2); });
  it('anulowanie edycji nie wysyła requestu i przywraca pusty formularz', async () => { renderPage(); await screen.findByText('Zabawne'); await userEvent.click(screen.getByRole('button', { name: 'Edytuj' })); expect(screen.getByLabelText('Nazwa PL')).toHaveValue('Zabawne'); await userEvent.click(screen.getByRole('button', { name: 'Anuluj' })); expect(screen.getByLabelText('Nazwa PL')).toHaveValue(''); expect(adminContentApi.updateCategory).not.toHaveBeenCalled(); });
  it('tworzenie przekazuje pełny payload i nowy token pakietu', async () => { vi.mocked(adminContentApi.createCategory).mockResolvedValue({ category: { ...category, id: 'c2', key: 'new', namePl: 'Nowa', nameEn: 'New' }, packageConcurrencyToken: 'pt2' }); renderPage(); await screen.findByText('Zabawne'); await userEvent.type(screen.getByLabelText('Key'), 'new'); await userEvent.type(screen.getByLabelText('Nazwa PL'), 'Nowa'); await userEvent.type(screen.getByLabelText('Nazwa EN'), 'New'); await userEvent.click(screen.getByRole('button', { name: 'Zapisz' })); await waitFor(() => expect(adminContentApi.createCategory).toHaveBeenCalledWith('p1', expect.objectContaining({ key: 'new', namePl: 'Nowa', nameEn: 'New', descriptionPl: '', descriptionEn: '', isActive: true, packageConcurrencyToken: 'pt1' }))); });
  it('usuwa pustą kategorię trybem reject', async () => { vi.mocked(adminContentApi.deleteCategory).mockResolvedValue({ success: true, packageConcurrencyToken: 'pt2' }); renderPage(); await screen.findByText('Zabawne'); await userEvent.click(screen.getByRole('button', { name: 'Usuń' })); const dialog = within(screen.getByRole('dialog')); expect(screen.getByRole('dialog')).toHaveTextContent('pustą kategorię'); await userEvent.click(dialog.getByRole('button', { name: 'Usuń' })); await waitFor(() => expect(adminContentApi.deleteCategory).toHaveBeenCalledWith('p1', 'c1', 'reject', 'ct1', 'pt1', undefined)); expect(screen.queryByText('Zabawne')).not.toBeInTheDocument(); });
  it('wymaga celu do przeniesienia pytań i wyklucza źródło', async () => { const withQuestions = { ...category, id: 'a', namePl: 'A', questionCount: 2 }; const target = { ...category, id: 'b', namePl: 'B', key: 'b' }; vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [withQuestions, target], packageConcurrencyToken: 'pt1' }); renderPage(); await screen.findByText('A'); await userEvent.click(within(screen.getAllByRole('listitem')[0]).getByRole('button', { name: 'Usuń' })); const dialog = within(screen.getByRole('dialog')); expect(dialog.getByRole('button', { name: 'Przenieś pytania' })).toBeDisabled(); expect(dialog.queryByRole('option', { name: 'A' })).not.toBeInTheDocument(); await userEvent.selectOptions(screen.getByLabelText('Kategoria docelowa'), 'b'); expect(dialog.getByRole('button', { name: 'Przenieś pytania' })).toBeEnabled(); });
  it('deleteQuestions usuwa kategorię dopiero po kliknięciu potwierdzenia', async () => { const withQuestions = { ...category, questionCount: 3 }; vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [withQuestions], packageConcurrencyToken: 'pt1' }); vi.mocked(adminContentApi.deleteCategory).mockResolvedValue({ success: true, packageConcurrencyToken: 'pt2' }); renderPage(); await screen.findByText('Zabawne'); await userEvent.click(screen.getByRole('button', { name: 'Usuń' })); expect(adminContentApi.deleteCategory).not.toHaveBeenCalled(); await userEvent.click(screen.getByRole('button', { name: 'Usuń kategorię i pytania' })); await waitFor(() => expect(adminContentApi.deleteCategory).toHaveBeenCalledWith('p1', 'c1', 'deleteQuestions', 'ct1', 'pt1', undefined)); });
  it('reorder wysyła pełną listę i przy błędzie przywraca widok', async () => { const second = { ...category, id: 'c2', key: 'two', namePl: 'Drugie', sortOrder: 1, concurrencyToken: 'ct2' }; vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [category, second], packageConcurrencyToken: 'pt1' }); vi.mocked(adminContentApi.reorderCategories).mockRejectedValue(new Error('Nie udało się')); renderPage(); await screen.findByText('Drugie'); await userEvent.click(within(screen.getAllByRole('listitem')[1]).getByRole('button', { name: 'Przenieś wyżej' })); await waitFor(() => expect(adminContentApi.reorderCategories).toHaveBeenCalledWith('p1', 'pt1', [{ id: 'c2', sortOrder: 0 }, { id: 'c1', sortOrder: 1 }])); expect(await screen.findByRole('alert')).toHaveTextContent('Nie udało się'); });
  it.each(['Archived', 'Published'] as const)('wersja %s jest tylko do odczytu', async status => { vi.mocked(adminContentApi.getPackage).mockResolvedValue({ id: 'p1', logicalPackageId: 'l1', version: 1, key: 'p', namePl: 'P', nameEn: 'P', status, isActive: true, categoryCount: 1, questionCount: 0, concurrencyToken: 'pt1' }); renderPage(); await screen.findByText(/tylko do odczytu/); expect(screen.queryByRole('button', { name: 'Usuń' })).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Wyłącz' })).not.toBeInTheDocument(); });
  it.each(['<img src=x onerror=alert(1)>', 'zwykły < tekst'])('renderuje plain text %s', async value => { vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [{ ...category, namePl: value }], packageConcurrencyToken: 'pt1' }); renderPage(); expect(await screen.findByText(value)).toBeInTheDocument(); });
  it('renderuje polski tekst, emoji i nową linię bez interpretacji HTML', async () => { vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [{ ...category, namePl: 'Zażółć 🥳\nnowa linia' }], packageConcurrencyToken: 'pt1' }); renderPage(); const name = await screen.findByText((_, element) => element?.tagName === 'STRONG' && element.textContent === 'Zażółć 🥳\nnowa linia'); expect(name).toBeInTheDocument(); });
  it('przenosi pytania do wskazanej kategorii i usuwa źródło z listy', async () => { const source = { ...category, id: 'a', key: 'a', namePl: 'A', questionCount: 2 }; const target = { ...category, id: 'b', key: 'b', namePl: 'B' }; vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [source, target], packageConcurrencyToken: 'pt1' }); vi.mocked(adminContentApi.deleteCategory).mockResolvedValue({ success: true, packageConcurrencyToken: 'pt2' }); renderPage(); await screen.findByText('A'); await userEvent.click(within(screen.getAllByRole('listitem')[0]).getByRole('button', { name: 'Usuń' })); await userEvent.selectOptions(screen.getByLabelText('Kategoria docelowa'), 'b'); await userEvent.click(screen.getByRole('button', { name: 'Przenieś pytania' })); await waitFor(() => expect(adminContentApi.deleteCategory).toHaveBeenCalledWith('p1', 'a', 'moveQuestions', 'ct1', 'pt1', 'b')); expect(screen.queryByText('A')).not.toBeInTheDocument(); });
  it('pozostawia dialog usuwania otwarty po błędzie API', async () => { vi.mocked(adminContentApi.deleteCategory).mockRejectedValue(new Error('Usunięcie odrzucone')); renderPage(); await screen.findByText('Zabawne'); await userEvent.click(screen.getByRole('button', { name: 'Usuń' })); await userEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Usuń' })); expect(await screen.findByRole('alert')).toHaveTextContent('Usunięcie odrzucone'); expect(screen.getByRole('dialog')).toBeInTheDocument(); });
  it('obsługuje Escape i ustawia fokus na dialogu usuwania', async () => { renderPage(); await screen.findByText('Zabawne'); await userEvent.click(screen.getByRole('button', { name: 'Usuń' })); const dialog = screen.getByRole('dialog'); await waitFor(() => expect(dialog).toHaveFocus()); await userEvent.keyboard('{Escape}'); expect(screen.queryByRole('dialog')).not.toBeInTheDocument(); });
  it('blokuje przyciski reorder na granicach listy', async () => { const second = { ...category, id: 'c2', key: 'two', namePl: 'Drugie', sortOrder: 1 }; vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [category, second], packageConcurrencyToken: 'pt1' }); renderPage(); await screen.findByText('Drugie'); const rows = screen.getAllByRole('listitem'); expect(within(rows[0]).getByRole('button', { name: 'Przenieś wyżej' })).toBeDisabled(); expect(within(rows[1]).getByRole('button', { name: 'Przenieś niżej' })).toBeDisabled(); });
  it('blokuje ponowne wysłanie formularza podczas zapisu', async () => { let resolveCreate: (value: { category: Category; packageConcurrencyToken: string }) => void = () => undefined; vi.mocked(adminContentApi.createCategory).mockImplementationOnce(() => new Promise(resolve => { resolveCreate = resolve; })); renderPage(); await screen.findByText('Zabawne'); await userEvent.type(screen.getByLabelText('Key'), 'new'); await userEvent.type(screen.getByLabelText('Nazwa PL'), 'Nowa'); await userEvent.type(screen.getByLabelText('Nazwa EN'), 'New'); await userEvent.click(screen.getByRole('button', { name: 'Zapisz' })); expect(screen.getByRole('button', { name: 'Zapisywanie…' })).toBeDisabled(); expect(adminContentApi.createCategory).toHaveBeenCalledTimes(1); resolveCreate({ category: { ...category, id: 'c2', key: 'new', namePl: 'Nowa', nameEn: 'New' }, packageConcurrencyToken: 'pt2' }); expect(await screen.findByRole('status')).toHaveTextContent('dodana'); });
  it.each(['Key', 'Nazwa PL', 'Nazwa EN'])('wymaga pola %s przed utworzeniem', async label => { renderPage(); await screen.findByText('Zabawne'); expect(screen.getByLabelText(label)).toBeInvalid(); await userEvent.click(screen.getByRole('button', { name: 'Zapisz' })); expect(adminContentApi.createCategory).not.toHaveBeenCalled(); });
  it('egzekwuje długość pola Key i nieujemny SortOrder w przeglądarce', async () => { renderPage(); await screen.findByText('Zabawne'); const key = screen.getByLabelText('Key'); await userEvent.type(key, 'x'.repeat(80)); expect(key).toHaveValue('x'.repeat(64)); const order = screen.getByLabelText('SortOrder'); fireEvent.change(order, { target: { value: '-1' } }); expect(order).toBeInvalid(); });
  it('pokazuje błąd tworzenia przy zachowaniu danych i opisu dla czytnika ekranu', async () => { vi.mocked(adminContentApi.createCategory).mockRejectedValue(new Error('Nieprawidłowy key')); renderPage(); await screen.findByText('Zabawne'); await userEvent.type(screen.getByLabelText('Key'), 'new'); await userEvent.type(screen.getByLabelText('Nazwa PL'), 'Nowa'); await userEvent.type(screen.getByLabelText('Nazwa EN'), 'New'); await userEvent.click(screen.getByRole('button', { name: 'Zapisz' })); expect(await screen.findByRole('alert')).toHaveTextContent('Nieprawidłowy key'); expect(screen.getByLabelText('Key')).toHaveValue('new'); expect(screen.getByLabelText('Key')).toHaveAttribute('aria-describedby', 'category-form-error'); expect(screen.getByRole('button', { name: 'Zapisz' })).toBeEnabled(); });
  it('zapisuje wszystkie pola edytowanej kategorii', async () => { const changed = { ...category, key: 'nowe', namePl: 'Nowe PL', nameEn: 'New EN', descriptionPl: 'Opis PL', descriptionEn: 'Description', isActive: false, sortOrder: 4, concurrencyToken: 'ct2' }; vi.mocked(adminContentApi.updateCategory).mockResolvedValue({ category: changed, packageConcurrencyToken: 'pt2' }); renderPage(); await screen.findByText('Zabawne'); await userEvent.click(screen.getByRole('button', { name: 'Edytuj' })); await userEvent.clear(screen.getByLabelText('Key')); await userEvent.type(screen.getByLabelText('Key'), 'nowe'); await userEvent.clear(screen.getByLabelText('Nazwa PL')); await userEvent.type(screen.getByLabelText('Nazwa PL'), 'Nowe PL'); await userEvent.clear(screen.getByLabelText('Nazwa EN')); await userEvent.type(screen.getByLabelText('Nazwa EN'), 'New EN'); await userEvent.type(screen.getByLabelText('Opis PL'), 'Opis PL'); await userEvent.type(screen.getByLabelText('Opis EN'), 'Description'); await userEvent.clear(screen.getByLabelText('SortOrder')); await userEvent.type(screen.getByLabelText('SortOrder'), '4'); await userEvent.click(screen.getByLabelText('Aktywna')); await userEvent.click(screen.getByRole('button', { name: 'Zapisz' })); await waitFor(() => expect(adminContentApi.updateCategory).toHaveBeenCalledWith('p1', 'c1', { key: 'nowe', namePl: 'Nowe PL', nameEn: 'New EN', descriptionPl: 'Opis PL', descriptionEn: 'Description', isActive: false, sortOrder: 4, concurrencyToken: 'ct1', packageConcurrencyToken: 'pt1' })); expect(screen.getByText('Nowe PL')).toBeInTheDocument(); });
  it('odświeża formularz po konflikcie i używa nowych tokenów', async () => { const refreshed = { ...category, namePl: 'Dane serwera', concurrencyToken: 'ct2' }; vi.mocked(adminContentApi.listCategories).mockResolvedValueOnce({ items: [category], packageConcurrencyToken: 'pt1' }).mockResolvedValueOnce({ items: [refreshed], packageConcurrencyToken: 'pt2' }); vi.mocked(adminContentApi.getPackage).mockResolvedValue({ id: 'p1', logicalPackageId: 'l1', version: 1, key: 'p', namePl: 'P', nameEn: 'P', status: 'Draft', isActive: true, categoryCount: 1, questionCount: 0, concurrencyToken: 'pt2' }); vi.mocked(adminContentApi.updateCategory).mockRejectedValueOnce(new AdminContentApiError(409, 'Konflikt')).mockResolvedValueOnce({ category: refreshed, packageConcurrencyToken: 'pt3' }); renderPage(); await screen.findByText('Zabawne'); await userEvent.click(screen.getByRole('button', { name: 'Edytuj' })); await userEvent.click(screen.getByRole('button', { name: 'Zapisz' })); await screen.findByRole('alert'); await userEvent.click(screen.getByRole('button', { name: 'Odśwież dane' })); await waitFor(() => expect(screen.getByLabelText('Nazwa PL')).toHaveValue('Dane serwera')); await userEvent.click(screen.getByRole('button', { name: 'Zapisz' })); await waitFor(() => expect(adminContentApi.updateCategory).toHaveBeenLastCalledWith('p1', 'c1', expect.objectContaining({ concurrencyToken: 'ct2', packageConcurrencyToken: 'pt2' }))); });
  it('włącza kategorię, zmienia widoczny status i zachowuje tokeny odpowiedzi', async () => { const inactive = { ...category, isActive: false, concurrencyToken: 'ct1' }; const active = { ...inactive, isActive: true, concurrencyToken: 'ct2' }; vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [inactive], packageConcurrencyToken: 'pt1' }); vi.mocked(adminContentApi.updateCategory).mockResolvedValueOnce({ category: active, packageConcurrencyToken: 'pt2' }).mockResolvedValueOnce({ category: { ...active, isActive: false }, packageConcurrencyToken: 'pt3' }); renderPage(); await screen.findByText('Włącz'); await userEvent.click(screen.getByRole('button', { name: 'Włącz' })); expect(await within(screen.getByRole('listitem')).findByText(/Aktywna/)).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Wyłącz' })); await waitFor(() => expect(adminContentApi.updateCategory).toHaveBeenLastCalledWith('p1', 'c1', expect.objectContaining({ concurrencyToken: 'ct2', packageConcurrencyToken: 'pt2', isActive: false }))); });
  it('anulowanie usuwania nie wysyła requestu i zwraca fokus do wyzwalacza', async () => { renderPage(); await screen.findByText('Zabawne'); const trigger = screen.getByRole('button', { name: 'Usuń' }); await userEvent.click(trigger); await userEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Anuluj' })); expect(adminContentApi.deleteCategory).not.toHaveBeenCalled(); await waitFor(() => expect(trigger).toHaveFocus()); });
  it('pokazuje liczbę pytań i utrzymuje kategorię po błędzie deleteQuestions', async () => { const withQuestions = { ...category, questionCount: 7 }; vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [withQuestions], packageConcurrencyToken: 'pt1' }); vi.mocked(adminContentApi.deleteCategory).mockRejectedValue(new Error('content_category_has_questions: 7')); renderPage(); await screen.findByText('Zabawne'); await userEvent.click(screen.getByRole('button', { name: 'Usuń' })); expect(screen.getByRole('dialog')).toHaveTextContent('7 pytań'); await userEvent.click(screen.getByRole('button', { name: 'Usuń kategorię i pytania' })); expect(await screen.findByRole('alert')).toHaveTextContent('7'); expect(screen.getByText('Zabawne')).toBeInTheDocument(); expect(screen.getByRole('dialog')).toBeInTheDocument(); });
  it('zachowuje kolejność i tokeny zwrócone przez udany reorder', async () => { const second = { ...category, id: 'c2', key: 'two', namePl: 'Drugie', sortOrder: 1, concurrencyToken: 'ct2' }; const reordered = [{ ...second, sortOrder: 0, concurrencyToken: 'ct3' }, { ...category, sortOrder: 1, concurrencyToken: 'ct4' }]; vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [category, second], packageConcurrencyToken: 'pt1' }); vi.mocked(adminContentApi.reorderCategories).mockResolvedValue({ items: reordered, packageConcurrencyToken: 'pt2' }); vi.mocked(adminContentApi.updateCategory).mockResolvedValue({ category: { ...reordered[0], isActive: false }, packageConcurrencyToken: 'pt3' }); renderPage(); await screen.findByText('Drugie'); await userEvent.click(within(screen.getAllByRole('listitem')[1]).getByRole('button', { name: 'Przenieś wyżej' })); await waitFor(() => expect(screen.getAllByRole('listitem')[0]).toHaveTextContent('Drugie')); await userEvent.click(within(screen.getAllByRole('listitem')[0]).getByRole('button', { name: 'Wyłącz' })); await waitFor(() => expect(adminContentApi.updateCategory).toHaveBeenCalledWith('p1', 'c2', expect.objectContaining({ concurrencyToken: 'ct3', packageConcurrencyToken: 'pt2' }))); });
  /* eslint-disable testing-library/no-node-access -- weryfikujemy wymagany stan rzeczywistego DOM dla payloadu XSS. */
  it('nie interpretuje payloadów XSS jako elementów DOM', async () => { vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [{ ...category, namePl: '<img src=x onerror=alert(1)>' }], packageConcurrencyToken: 'pt1' }); renderPage(); await screen.findByText('<img src=x onerror=alert(1)>'); expect(document.querySelector('script')).toBeNull(); expect(document.querySelector('img')).toBeNull(); });
  /* eslint-enable testing-library/no-node-access */
  it('otwiera edycję klawiaturą', async () => { renderPage(); await screen.findByText('Zabawne'); const edit = screen.getByRole('button', { name: 'Edytuj' }); edit.focus(); await userEvent.keyboard('{Enter}'); expect(screen.getByLabelText('Nazwa PL')).toHaveValue('Zabawne'); });
  it('zachowuje widoczny stan po błędzie wyłączania i pokazuje konflikt', async () => { vi.mocked(adminContentApi.updateCategory).mockRejectedValue(new AdminContentApiError(409, 'Konflikt wyłączania')); renderPage(); await screen.findByText('Zabawne'); await userEvent.click(screen.getByRole('button', { name: 'Wyłącz' })); expect(await screen.findByRole('alert')).toHaveTextContent('Konflikt wyłączania'); expect(within(screen.getByRole('listitem')).getByText(/Aktywna/)).toBeInTheDocument(); });
  it('blokuje reorder podczas oczekiwania na odpowiedź', async () => { const second = { ...category, id: 'c2', key: 'two', namePl: 'Drugie', sortOrder: 1 }; let resolveReorder: (value: { items: Category[]; packageConcurrencyToken: string }) => void = () => undefined; vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [category, second], packageConcurrencyToken: 'pt1' }); vi.mocked(adminContentApi.reorderCategories).mockImplementationOnce(() => new Promise(resolve => { resolveReorder = resolve; })); renderPage(); await screen.findByText('Drugie'); await userEvent.click(within(screen.getAllByRole('listitem')[1]).getByRole('button', { name: 'Przenieś wyżej' })); expect(screen.getAllByRole('button', { name: /Przenieś/ }).every(button => button.hasAttribute('disabled'))).toBe(true); resolveReorder({ items: [second, category], packageConcurrencyToken: 'pt2' }); await waitFor(() => expect(screen.getAllByRole('listitem')[0]).toHaveTextContent('Drugie')); });
});
