import { useCallback, useEffect, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import { useParams } from 'react-router-dom';
import { AdminContentApiError, adminContentApi, type Category, type PackageStatus } from '../../api/adminContentApi';

type CategoryForm = Pick<Category, 'key' | 'namePl' | 'nameEn' | 'descriptionPl' | 'descriptionEn' | 'isActive' | 'sortOrder'>;
const blank = (sortOrder = 0): CategoryForm => ({ key: '', namePl: '', nameEn: '', descriptionPl: '', descriptionEn: '', isActive: true, sortOrder });

export function CategoryManager() {
  const { packageVersionId = '' } = useParams();
  const [items, setItems] = useState<Category[]>([]); const [packageToken, setPackageToken] = useState(''); const [status, setStatus] = useState<PackageStatus>('Draft');
  const [form, setForm] = useState<CategoryForm>(blank()); const [editing, setEditing] = useState<Category>(); const [deleting, setDeleting] = useState<Category>(); const [targetId, setTargetId] = useState(''); const [deleteTriggerId, setDeleteTriggerId] = useState<string>(); const dialogRef = useRef<HTMLDivElement>(null); const deleteTriggerRef = useRef<HTMLButtonElement>(null);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>(); const [success, setSuccess] = useState<string>(); const [conflict, setConflict] = useState(false);
  const readOnly = status !== 'Draft';
  const load = useCallback(async () => { setLoading(true); try { const [categories, pkg] = await Promise.all([adminContentApi.listCategories(packageVersionId), adminContentApi.getPackage(packageVersionId)]); setItems(categories.items); setPackageToken(categories.packageConcurrencyToken); setStatus(pkg.status); if (editing) { const latest = categories.items.find(x => x.id === editing.id); if (latest) { setEditing(latest); setForm({ key: latest.key, namePl: latest.namePl, nameEn: latest.nameEn, descriptionPl: latest.descriptionPl, descriptionEn: latest.descriptionEn, isActive: latest.isActive, sortOrder: latest.sortOrder }); } } setError(undefined); setConflict(false); } catch (cause) { setError(message(cause)); } finally { setLoading(false); } }, [editing, packageVersionId]);
  useEffect(() => { let active = true; void Promise.all([adminContentApi.listCategories(packageVersionId), adminContentApi.getPackage(packageVersionId)]).then(([categories, pkg]) => { if (active) { setItems(categories.items); setPackageToken(categories.packageConcurrencyToken); setStatus(pkg.status); } }).catch((cause: unknown) => { if (active) setError(message(cause)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [packageVersionId]);
  useEffect(() => { if (!deleting) return; dialogRef.current?.focus(); const closeOnEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') { setDeleting(undefined); setTargetId(''); setDeleteTriggerId(undefined); deleteTriggerRef.current?.focus(); } }; document.addEventListener('keydown', closeOnEscape); return () => document.removeEventListener('keydown', closeOnEscape); }, [deleting]);
  const fail = (cause: unknown) => { setError(message(cause)); setConflict(cause instanceof AdminContentApiError && cause.status === 409); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(undefined); try { if (editing) { const result = await adminContentApi.updateCategory(packageVersionId, editing.id, { ...form, concurrencyToken: editing.concurrencyToken, packageConcurrencyToken: packageToken }); setItems(current => current.map(x => x.id === editing.id ? result.category : x)); setPackageToken(result.packageConcurrencyToken); setEditing(undefined); setSuccess('Kategoria została zapisana.'); } else { const result = await adminContentApi.createCategory(packageVersionId, { ...form, packageConcurrencyToken: packageToken }); setItems(current => [...current, result.category]); setPackageToken(result.packageConcurrencyToken); setSuccess('Kategoria została dodana.'); } setForm(blank(items.length + 1)); } catch (cause) { fail(cause); } finally { setBusy(false); } };
  const edit = (item: Category) => { setEditing(item); setForm({ key: item.key, namePl: item.namePl, nameEn: item.nameEn, descriptionPl: item.descriptionPl, descriptionEn: item.descriptionEn, isActive: item.isActive, sortOrder: item.sortOrder }); setError(undefined); };
  const toggle = async (item: Category) => { setBusy(true); try { const result = await adminContentApi.updateCategory(packageVersionId, item.id, { isActive: !item.isActive, concurrencyToken: item.concurrencyToken, packageConcurrencyToken: packageToken }); setItems(current => current.map(x => x.id === item.id ? result.category : x)); setPackageToken(result.packageConcurrencyToken); setSuccess(result.category.isActive ? 'Kategoria została włączona.' : 'Kategoria została wyłączona.'); } catch (cause) { fail(cause); } finally { setBusy(false); } };
  const remove = async (mode: 'reject' | 'deleteQuestions' | 'moveQuestions') => { if (!deleting) return; setBusy(true); try { const result = await adminContentApi.deleteCategory(packageVersionId, deleting.id, mode, deleting.concurrencyToken, packageToken, targetId || undefined); setPackageToken(result.packageConcurrencyToken); setItems(current => current.filter(x => x.id !== deleting.id)); setDeleting(undefined); setTargetId(''); setSuccess('Kategoria została usunięta.'); } catch (cause) { fail(cause); } finally { setBusy(false); } };
  const move = async (index: number, delta: number) => { const target = index + delta; if (target < 0 || target >= items.length) return; const previous = items; const next = [...items]; [next[index], next[target]] = [next[target], next[index]]; setItems(next); setBusy(true); try { const result = await adminContentApi.reorderCategories(packageVersionId, packageToken, next.map((x, i) => ({ id: x.id, sortOrder: i }))); setItems(result.items); setPackageToken(result.packageConcurrencyToken); } catch (cause) { setItems(previous); fail(cause); } finally { setBusy(false); } };
  if (loading) return <p aria-live="polite">Wczytywanie kategorii…</p>;
  return <section className="category-manager"><h2>Kategorie</h2>
    {readOnly && <p className="notice">Ta wersja pakietu jest tylko do odczytu. Utwórz nową wersję roboczą, aby wprowadzić zmiany.</p>}
    {error && <div id="category-form-error" role="alert" className="error-banner">{error} <button type="button" onClick={() => void load()}>Odśwież dane</button>{conflict && <button type="button" onClick={() => setConflict(false)}>Pozostań przy wpisanych zmianach</button>}</div>}{success && <p role="status">{success}</p>}
    {!readOnly && <form onSubmit={e => void submit(e)}><label>Key<input value={form.key} onChange={e => setForm({ ...form, key: e.target.value })} required maxLength={64} aria-describedby={error ? 'category-form-error' : undefined}/></label><label>Nazwa PL<input value={form.namePl} onChange={e => setForm({ ...form, namePl: e.target.value })} required maxLength={120} aria-describedby={error ? 'category-form-error' : undefined}/></label><label>Nazwa EN<input value={form.nameEn} onChange={e => setForm({ ...form, nameEn: e.target.value })} required maxLength={120} aria-describedby={error ? 'category-form-error' : undefined}/></label><label>Opis PL<textarea value={form.descriptionPl} onChange={e => setForm({ ...form, descriptionPl: e.target.value })} maxLength={1000} aria-describedby={error ? 'category-form-error' : undefined}/></label><label>Opis EN<textarea value={form.descriptionEn} onChange={e => setForm({ ...form, descriptionEn: e.target.value })} maxLength={1000} aria-describedby={error ? 'category-form-error' : undefined}/></label><label>SortOrder<input type="number" min="0" value={form.sortOrder} onChange={e => setForm({ ...form, sortOrder: Number(e.target.value) })} aria-describedby={error ? 'category-form-error' : undefined}/></label><label><input type="checkbox" checked={form.isActive} onChange={e => setForm({ ...form, isActive: e.target.checked })}/> Aktywna</label><button disabled={busy}>{busy ? 'Zapisywanie…' : 'Zapisz'}</button>{editing && <button type="button" onClick={() => { setEditing(undefined); setForm(blank(items.length)); }}>Anuluj</button>}</form>}
    {items.length === 0 ? <p>Ten pakiet nie ma jeszcze kategorii. Dodaj pierwszą kategorię, aby rozpocząć tworzenie treści.</p> : <ul>{items.map((item, index) => <li key={item.id}><strong>{item.namePl}</strong><span>{item.nameEn} · {item.key} · {item.questionCount} pytań · {item.isActive ? 'Aktywna' : 'Wyłączona'}</span>{!readOnly && <div><button disabled={busy} onClick={() => edit(item)}>Edytuj</button><button disabled={busy} onClick={() => void toggle(item)}>{item.isActive ? 'Wyłącz' : 'Włącz'}</button><button disabled={busy || index === 0} onClick={() => void move(index, -1)}>Przenieś wyżej</button><button disabled={busy || index === items.length - 1} onClick={() => void move(index, 1)}>Przenieś niżej</button><button ref={deleteTriggerId === item.id ? deleteTriggerRef : undefined} disabled={busy} onClick={() => { setDeleteTriggerId(item.id); setDeleting(item); }}>Usuń</button></div>}</li>)}</ul>}
    {deleting && <div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="delete-title" tabIndex={-1}><h3 id="delete-title">Usuń kategorię</h3><p>{deleting.questionCount ? `Ta kategoria zawiera ${deleting.questionCount} pytań.` : 'Czy usunąć pustą kategorię?'}</p>{deleting.questionCount > 0 && <><label>Kategoria docelowa<select value={targetId} onChange={e => setTargetId(e.target.value)}><option value="">Wybierz…</option>{items.filter(x => x.id !== deleting.id).map(x => <option key={x.id} value={x.id}>{x.namePl}</option>)}</select></label><button disabled={!targetId || busy} onClick={() => void remove('moveQuestions')}>Przenieś pytania</button><button disabled={busy} onClick={() => void remove('deleteQuestions')}>Usuń kategorię i pytania</button></>}{deleting.questionCount === 0 && <button disabled={busy} onClick={() => void remove('reject')}>Usuń</button>}<button onClick={() => { setDeleting(undefined); setTargetId(''); setDeleteTriggerId(undefined); deleteTriggerRef.current?.focus(); }}>Anuluj</button></div>}
  </section>;
}
function message(cause: unknown) { return cause instanceof Error ? cause.message : 'Operacja nie powiodła się.'; }
