import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { AdminContentApiError, adminContentApi, type ContentPackage } from '../../api/adminContentApi';

const message = (cause: unknown) => cause instanceof Error ? cause.message : 'Operacja nie powiodła się.';
export function PackageOverviewPage() {
  const { packageVersionId = '' } = useParams(); const navigate = useNavigate(); const [item, setItem] = useState<ContentPackage>(); const [form, setForm] = useState({ namePl: '', nameEn: '', descriptionPl: '', descriptionEn: '' }); const [error, setError] = useState<string>(); const [dirty, setDirty] = useState(false); const [busy, setBusy] = useState(false); const [dialog, setDialog] = useState<'publish' | 'archive'>(); const [validationErrors, setValidationErrors] = useState<{ path: string; code: string; message: string }[]>([]);
  const load = useCallback(async () => { try { const value = await adminContentApi.getPackage(packageVersionId); setItem(value); setForm({ namePl: value.namePl, nameEn: value.nameEn, descriptionPl: value.descriptionPl ?? '', descriptionEn: value.descriptionEn ?? '' }); setDirty(false); setError(undefined); } catch (cause) { setError(message(cause)); } }, [packageVersionId]);
  // eslint-disable-next-line react-hooks/set-state-in-effect -- dane pakietu są synchronizowane z API po zmianie trasy.
  useEffect(() => { void load(); }, [load]); useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ''; } }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
  if (!item) return <p>Wczytywanie pakietu…</p>; const readOnly = item.status !== 'Draft';
  const fail = (cause: unknown) => { const api = cause instanceof AdminContentApiError ? cause : undefined; const body = api?.body as { errors?: { path: string; code: string; message: string }[] } | undefined; setValidationErrors(body?.errors ?? []); setError(api?.status === 409 ? 'Pakiet został zmieniony w innej sesji.' : message(cause)); };
  const save = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { const result = await adminContentApi.updatePackage(item.id, { ...form, concurrencyToken: item.concurrencyToken }); setItem(result); setDirty(false); } catch (cause) { fail(cause); } finally { setBusy(false); } };
  const publish = async () => { setBusy(true); try { const result = await adminContentApi.publish(item.id, item.concurrencyToken); setItem(result); setDialog(undefined); setDirty(false); } catch (cause) { fail(cause); } finally { setBusy(false); } };
  const archive = async () => { setBusy(true); try { const result = await adminContentApi.archive(item.id, item.concurrencyToken); setItem(result); setDialog(undefined); } catch (cause) { fail(cause); } finally { setBusy(false); } };
  const createDraft = async () => { setBusy(true); try { const draft = await adminContentApi.createDraft(item.id); navigate(`/admin/content/packages/${draft.id}`); } catch (cause) { fail(cause); } finally { setBusy(false); } };
  const activeCategories = item.categoryCount; const activeQuestions = item.questionCount; const typeDistribution = Object.entries(item.questionCountByType ?? {}).map(([type, count]) => `${type}: ${count}`).join(', ') || 'Brak pytań';
  return <section><header><div><p className="eyebrow">{item.status} · v{item.version}</p><h2>{item.namePl}</h2></div><Link to="/admin/content">Wróć do pakietów</Link></header>{error && <div role="alert" className="error-banner">{error} <button onClick={() => void load()}>Odśwież dane</button></div>}
    <dl className="package-details"><dt>Rodzina</dt><dd>{item.logicalPackageId}</dd><dt>Wersja</dt><dd>{item.version}</dd><dt>Kategorie</dt><dd>{item.categoryCount}</dd><dt>Pytania</dt><dd>{item.questionCount}</dd><dt>Typy pytań</dt><dd>{typeDistribution}</dd><dt>Opublikowano</dt><dd>{item.publishedAtUtc ?? '—'}</dd><dt>Zarchiwizowano</dt><dd>{item.archivedAtUtc ?? '—'}</dd></dl>
    {readOnly ? <p className="notice">Ta wersja pakietu jest tylko do odczytu. Utwórz nową wersję roboczą, aby wprowadzić zmiany.</p> : <form onSubmit={save}><label>Nazwa PL<input value={form.namePl} maxLength={120} onChange={event => { setForm({ ...form, namePl: event.target.value }); setDirty(true); }} /></label><label>Nazwa EN<input value={form.nameEn} maxLength={120} onChange={event => { setForm({ ...form, nameEn: event.target.value }); setDirty(true); }} /></label><label>Opis PL<textarea value={form.descriptionPl} maxLength={1000} onChange={event => { setForm({ ...form, descriptionPl: event.target.value }); setDirty(true); }} /></label><label>Opis EN<textarea value={form.descriptionEn} maxLength={1000} onChange={event => { setForm({ ...form, descriptionEn: event.target.value }); setDirty(true); }} /></label><button disabled={busy}>{busy ? 'Zapisywanie…' : 'Zapisz'}</button></form>}
    <div className="content-actions"><Link to="categories">Kategorie</Link><Link to="questions">Pytania</Link>{item.status === 'Draft' && <button disabled={busy} onClick={() => { setValidationErrors([]); setError(undefined); setDialog('publish'); }}>Publikuj</button>}{item.status === 'Published' && <><button disabled={busy} onClick={() => void createDraft()}>Utwórz Draft</button><button disabled={busy} onClick={() => { setValidationErrors([]); setError(undefined); setDialog('archive'); }}>Archiwizuj</button></>}{item.status === 'Archived' && <button disabled={busy} onClick={() => void createDraft()}>Utwórz Draft</button>}</div>
    {dialog === 'publish' && <div role="dialog" aria-modal="true" aria-labelledby="publish-title"><h3 id="publish-title">Opublikować pakiet?</h3><p>{item.namePl} · v{item.version}</p><p>{activeCategories} aktywnych kategorii · {activeQuestions} aktywnych pytań</p><p>Rozkład typów: {typeDistribution}</p>{validationErrors.length > 0 && <ul>{validationErrors.map(error => <li key={`${error.path}-${error.code}`}>{error.path}: {error.message}</li>)}</ul>}<button disabled={busy} onClick={() => void publish()}>Publikuj</button><button disabled={busy} onClick={() => setDialog(undefined)}>Anuluj</button></div>}
    {dialog === 'archive' && <div role="dialog" aria-modal="true" aria-labelledby="archive-title"><h3 id="archive-title">Zarchiwizować tę wersję pakietu?</h3><p>Nowe pokoje nie będą mogły jej użyć. Istniejące gry pozostaną bez zmian.</p><button disabled={busy} onClick={() => void archive()}>Archiwizuj</button><button disabled={busy} onClick={() => setDialog(undefined)}>Anuluj</button></div>}
  </section>;
}
