import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import { AdminContentApiError, adminContentApi, type Category, type PackageStatus, type Question, type QuestionType } from '../../api/adminContentApi';
import { QuestionPreview } from './QuestionPreview';

type Form = { categoryId: string; key: string; type: QuestionType; textPl: string; textEn: string; minimumPlayers: number; sortOrder: number; isActive: boolean };
const empty = (categoryId = ''): Form => ({ categoryId, key: '', type: 'PlayerSelection', textPl: '', textEn: '', minimumPlayers: 3, sortOrder: 0, isActive: true });
const types: QuestionType[] = ['PlayerSelection', 'TextAnswer', 'PhotoAnswer', 'DrawingAnswer'];
const help = (type: QuestionType) => ({ PlayerSelection: 'Wybierz gracza jako odpowiedź. Dozwolony placeholder: {player}.', TextAnswer: 'Gracze wpisują własną odpowiedź tekstową. Odpowiedzi są anonimowe.', PhotoAnswer: 'Gracze wykonują lub wybierają zdjęcie jako odpowiedź.', DrawingAnswer: 'Gracze rysują odpowiedź na prostym płótnie dotykowym.' })[type];
const limits = { key: 100, text: 500 };
const toForm = (question: Question): Form => ({ categoryId: question.categoryId, key: question.key, type: question.type, textPl: question.textPl, textEn: question.textEn, minimumPlayers: question.minimumPlayers, sortOrder: question.sortOrder, isActive: question.isActive });
const message = (cause: unknown) => cause instanceof Error ? cause.message : 'Operacja nie powiodła się.';

export function QuestionFormPage() {
  const { packageVersionId = '', questionId } = useParams(); const isNew = questionId === 'new' || !questionId; const { search } = useLocation(); const navigate = useNavigate();
  const [form, setForm] = useState<Form>(empty()); const [categories, setCategories] = useState<Category[]>([]); const [status, setStatus] = useState<PackageStatus>('Draft'); const [questionToken, setQuestionToken] = useState(''); const [packageToken, setPackageToken] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>(); const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({}); const [dirty, setDirty] = useState(false); const [confirmLeave, setConfirmLeave] = useState(false); const [conflict, setConflict] = useState(false); const dialogRef = useRef<HTMLDivElement>(null);
  const readOnly = status !== 'Draft'; const listPath = `/admin/content/packages/${packageVersionId}/questions${search}`;
  const load = useCallback(async (keepInput = false) => { setLoading(true); try { const [pkg, cats, detail] = await Promise.all([adminContentApi.getPackage(packageVersionId), adminContentApi.listCategories(packageVersionId), isNew ? Promise.resolve(undefined) : adminContentApi.getQuestion(packageVersionId, questionId!)]); setStatus(detail?.packageStatus ?? pkg.status); setCategories(cats.items); setPackageToken(detail?.packageConcurrencyToken ?? pkg.concurrencyToken); if (!keepInput) { if (detail) { setForm(toForm(detail.question)); setQuestionToken(detail.question.concurrencyToken); } else { const firstActive = cats.items.find(category => category.isActive); setForm(empty(firstActive?.id ?? cats.items[0]?.id ?? '')); } setDirty(false); } setError(undefined); setConflict(false); } catch (cause) { setError(message(cause)); } finally { setLoading(false); } }, [isNew, packageVersionId, questionId]);
  // eslint-disable-next-line react-hooks/set-state-in-effect -- formularz synchronizuje dane początkowe z API po zmianie trasy.
  useEffect(() => { void load(); }, [load]); useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty && !readOnly) { event.preventDefault(); event.returnValue = ''; } }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty, readOnly]); useEffect(() => { if (confirmLeave) dialogRef.current?.focus(); }, [confirmLeave]);
  const update = <K extends keyof Form>(key: K, value: Form[K]) => { setForm(current => ({ ...current, [key]: value })); setDirty(true); setFieldErrors(current => ({ ...current, [key]: '' })); };
  const validate = () => { const errors: Record<string, string> = {}; if (!form.categoryId) errors.categoryId = 'Wybierz kategorię.'; if (!form.key) errors.key = 'Key jest wymagany.'; else if (form.key.length > limits.key) errors.key = `Maksymalnie ${limits.key} znaków.`; else if (!/^[a-z][a-z0-9_]*$/.test(form.key)) errors.key = 'Użyj formatu lowercase_snake_case.'; if (!form.textPl) errors.textPl = 'Treść PL jest wymagana.'; else if (form.textPl.length > limits.text) errors.textPl = `Maksymalnie ${limits.text} znaków.`; if (!form.textEn) errors.textEn = 'Treść EN jest wymagana.'; else if (form.textEn.length > limits.text) errors.textEn = `Maksymalnie ${limits.text} znaków.`; if (form.minimumPlayers < 3) errors.minimumPlayers = 'Minimum wynosi 3.'; if (form.sortOrder < 0) errors.sortOrder = 'Kolejność nie może być ujemna.'; if (/\{\}|\{[^}]*$/.test(form.textPl) || /\{\}|\{[^}]*$/.test(form.textEn)) errors.textPl = errors.textPl ?? 'Placeholder jest niedomknięty lub pusty.'; if (form.type === 'PlayerSelection' && /\{(?!player(?::\d+)?\})[^}]*\}/i.test(`${form.textPl} ${form.textEn}`)) errors.textPl = errors.textPl ?? 'Dozwolony jest wyłącznie placeholder {player}.'; setFieldErrors(errors); return Object.keys(errors).length === 0; };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (readOnly || !validate()) return; setSaving(true); setError(undefined); try { if (isNew) { const created = await adminContentApi.createQuestion(packageVersionId, form); navigate(`/admin/content/packages/${packageVersionId}/questions/${created.id}${search}`, { replace: true }); } else { const result = await adminContentApi.updateQuestion(packageVersionId, questionId!, { ...form, concurrencyToken: questionToken, packageConcurrencyToken: packageToken }); setQuestionToken(result.question.concurrencyToken); setPackageToken(result.packageConcurrencyToken); setForm(toForm(result.question)); setDirty(false); } } catch (cause) { const api = cause instanceof AdminContentApiError ? cause : undefined; setConflict(api?.status === 409); const body = api?.body as { errors?: { path?: string; message?: string }[] } | undefined; const serverErrors = Object.fromEntries((body?.errors ?? []).filter(item => item.path && item.message).map(item => [item.path!, item.message!])); if (Object.keys(serverErrors).length) setFieldErrors(current => ({ ...current, ...serverErrors })); setError(api?.status === 409 ? 'To pytanie zostało zmienione w innej sesji.' : message(cause)); } finally { setSaving(false); } };
  const leave = () => { if (dirty && !readOnly) setConfirmLeave(true); else navigate(listPath); }; const selectedCategory = categories.find(category => category.id === form.categoryId);
  if (loading) return <p aria-live="polite">Wczytywanie pytania…</p>; if (!isNew && error && !questionToken) return <section><h2>Nie znaleziono pytania</h2><p role="alert">{error}</p><Link to={listPath}>Wróć do listy pytań</Link></section>;
  const field = (name: keyof Form) => fieldErrors[name] ? `question-${name}-error` : undefined;
  return <section className="question-form"><h2>{isNew ? 'Nowe pytanie' : 'Edycja pytania'}</h2>{readOnly && <p className="notice">Ta wersja pakietu jest tylko do odczytu. Utwórz nową wersję roboczą, aby edytować pytania.</p>}{error && <div role="alert">{error} {conflict && <><button type="button" onClick={() => void load()}>Odśwież dane</button><button type="button" onClick={() => { setConflict(false); setError(undefined); }}>Pozostań przy wpisanych zmianach</button></>}</div>}
    <form onSubmit={submit}><label>Typ pytania<select value={form.type} disabled={readOnly || saving} onChange={event => update('type', event.target.value as QuestionType)}>{types.map(type => <option key={type} value={type}>{type}</option>)}</select></label><p>{help(form.type)}</p><label>Kategoria<select value={form.categoryId} disabled={readOnly || saving} aria-describedby={field('categoryId')} onChange={event => update('categoryId', event.target.value)}><option value="">Wybierz…</option>{categories.map(category => <option key={category.id} value={category.id}>{category.namePl}{category.isActive ? '' : ' (wyłączona)'}</option>)}</select></label>{fieldErrors.categoryId && <p id={field('categoryId')} role="alert">{fieldErrors.categoryId}</p>}{selectedCategory && !selectedCategory.isActive && form.isActive && <p role="note">Aktywne pytanie jest przypisane do wyłączonej kategorii.</p>}<label>Key<input value={form.key} readOnly={readOnly || saving} maxLength={limits.key} aria-describedby={field('key')} onChange={event => update('key', event.target.value)} /></label><span>{form.key.length} / {limits.key}</span>{fieldErrors.key && <p id={field('key')} role="alert">{fieldErrors.key}</p>}<label>Tekst PL<textarea value={form.textPl} readOnly={readOnly || saving} maxLength={limits.text} aria-describedby={field('textPl')} onChange={event => update('textPl', event.target.value)} /></label><span>{form.textPl.length} / {limits.text}</span>{fieldErrors.textPl && <p id={field('textPl')} role="alert">{fieldErrors.textPl}</p>}<label>Tekst EN<textarea value={form.textEn} readOnly={readOnly || saving} maxLength={limits.text} aria-describedby={field('textEn')} onChange={event => update('textEn', event.target.value)} /></label><span>{form.textEn.length} / {limits.text}</span>{fieldErrors.textEn && <p id={field('textEn')} role="alert">{fieldErrors.textEn}</p>}<label>MinimumPlayers<input type="number" min="3" value={form.minimumPlayers} readOnly={readOnly || saving} aria-describedby={field('minimumPlayers')} onChange={event => update('minimumPlayers', Number(event.target.value))} /></label>{fieldErrors.minimumPlayers && <p id={field('minimumPlayers')} role="alert">{fieldErrors.minimumPlayers}</p>}<label>SortOrder<input type="number" min="0" value={form.sortOrder} readOnly={readOnly || saving} aria-describedby={field('sortOrder')} onChange={event => update('sortOrder', Number(event.target.value))} /></label>{fieldErrors.sortOrder && <p id={field('sortOrder')} role="alert">{fieldErrors.sortOrder}</p>}<label><input type="checkbox" checked={form.isActive} disabled={readOnly || saving} onChange={event => update('isActive', event.target.checked)} /> Aktywne</label>{!readOnly && <button disabled={saving}>{saving ? 'Zapisywanie…' : 'Zapisz'}</button>}<button type="button" onClick={leave}>{isNew ? 'Anuluj' : 'Wróć do listy'}</button></form><QuestionPreview type={form.type} textPl={form.textPl} textEn={form.textEn} />
    {confirmLeave && <div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="unsaved-title" tabIndex={-1}><h3 id="unsaved-title">Masz niezapisane zmiany.</h3><p>Czy na pewno chcesz opuścić formularz?</p><button onClick={() => setConfirmLeave(false)}>Zostań</button><button onClick={() => navigate(listPath)}>Opuść bez zapisywania</button></div>}
  </section>;
}
