import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { AdminContentApiError, adminContentApi, type Category, type ContentPackage, type Question } from '../../api/adminContentApi';
import { QuestionFormPage } from './QuestionFormPage';

vi.mock('../../api/adminContentApi', async original => { const actual = await original<typeof import('../../api/adminContentApi')>(); return { ...actual, adminContentApi: { getPackage: vi.fn(), listCategories: vi.fn(), getQuestion: vi.fn(), createQuestion: vi.fn(), updateQuestion: vi.fn() } }; });
const category: Category = { id: 'c1', packageId: 'p1', key: 'fun', namePl: 'Zabawne', nameEn: 'Funny', descriptionPl: '', descriptionEn: '', isActive: true, sortOrder: 0, questionCount: 1, concurrencyToken: 'ct1' };
const pkg: ContentPackage = { id: 'p1', logicalPackageId: 'l1', version: 1, key: 'p', namePl: 'P', nameEn: 'P', status: 'Draft', isActive: true, categoryCount: 1, questionCount: 1, concurrencyToken: 'pt1' };
const question: Question = { id: 'q1', packageId: 'p1', categoryId: 'c1', categoryKey: 'fun', categoryNamePl: 'Zabawne', key: 'fun_question', questionType: 'PlayerSelection', type: 'PlayerSelection', textPl: 'Wybierz {player}', textEn: 'Choose {player}', isActive: true, isEnabled: true, minimumPlayers: 3, sortOrder: 0, createdAtUtc: '2026-01-01T00:00:00Z', updatedAtUtc: '2026-01-01T00:00:00Z', concurrencyToken: 'qt1', validationErrors: [] };
const renderPage = (path = '/admin/content/packages/p1/questions/new?categoryId=c1') => render(<MemoryRouter initialEntries={[path]}><Routes><Route path="/admin/content/packages/:packageVersionId/questions/new" element={<QuestionFormPage />} /><Route path="/admin/content/packages/:packageVersionId/questions/:questionId" element={<QuestionFormPage />} /><Route path="/admin/content/packages/:packageVersionId/questions" element={<p>Lista</p>} /></Routes></MemoryRouter>);

describe('QuestionFormPage', () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(adminContentApi.getPackage).mockResolvedValue(pkg); vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [category], packageConcurrencyToken: 'pt1' }); vi.mocked(adminContentApi.getQuestion).mockResolvedValue({ question, packageConcurrencyToken: 'pt1', packageStatus: 'Draft' }); });
  it('tworzenie ustawia domyślne wartości, labelki i pusty preview', async () => { renderPage(); expect(screen.getByText('Wczytywanie pytania…')).toBeInTheDocument(); await screen.findByText('Nowe pytanie'); expect(screen.getByLabelText('Kategoria')).toHaveValue('c1'); expect(screen.getByLabelText('MinimumPlayers')).toHaveValue(3); expect(screen.getAllByText('Podgląd pojawi się po wpisaniu treści pytania.')).toHaveLength(2); });
  it('waliduje pola wymagane, format key i placeholder', async () => { renderPage(); await screen.findByText('Nowe pytanie'); await userEvent.click(screen.getByRole('button', { name: 'Zapisz' })); expect(screen.getByText('Key jest wymagany.')).toBeInTheDocument(); await userEvent.type(screen.getByLabelText('Key'), 'Bad key'); await userEvent.type(screen.getByLabelText('Tekst PL'), '{unknown}'); await userEvent.type(screen.getByLabelText('Tekst EN'), 'ok'); await userEvent.click(screen.getByRole('button', { name: 'Zapisz' })); expect(screen.getByText('Użyj formatu lowercase_snake_case.')).toBeInTheDocument(); expect(adminContentApi.createQuestion).not.toHaveBeenCalled(); });
  it('tworzy pytanie z pełnym payloadem i blokuje double submit', async () => { let resolveCreate: (value: Question) => void = () => undefined; vi.mocked(adminContentApi.createQuestion).mockImplementationOnce(() => new Promise(resolve => { resolveCreate = resolve; })); renderPage(); await screen.findByText('Nowe pytanie'); await userEvent.type(screen.getByLabelText('Key'), 'new_question'); await userEvent.type(screen.getByLabelText('Tekst PL'), 'Treść'); await userEvent.type(screen.getByLabelText('Tekst EN'), 'Text'); await userEvent.click(screen.getByRole('button', { name: 'Zapisz' })); expect(screen.getByRole('button', { name: 'Zapisywanie…' })).toBeDisabled(); expect(adminContentApi.createQuestion).toHaveBeenCalledWith('p1', expect.objectContaining({ categoryId: 'c1', key: 'new_question', minimumPlayers: 3, isActive: true })); resolveCreate({ ...question, id: 'new' }); });
  it('edytowanie wypełnia pola, zmienia typ i zapisuje aktualne tokeny', async () => { vi.mocked(adminContentApi.updateQuestion).mockResolvedValue({ question: { ...question, type: 'TextAnswer', questionType: 'TextAnswer', concurrencyToken: 'qt2' }, packageConcurrencyToken: 'pt2' }); renderPage('/admin/content/packages/p1/questions/q1'); await screen.findByDisplayValue('fun_question'); expect(screen.getByLabelText('Tekst PL')).toHaveValue('Wybierz {player}'); await userEvent.selectOptions(screen.getByLabelText('Typ pytania'), 'TextAnswer'); expect(within(screen.getByLabelText('Podgląd pytania')).getByText('Gracze wpisują własną odpowiedź tekstową.')).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Zapisz' })); await waitFor(() => expect(adminContentApi.updateQuestion).toHaveBeenCalledWith('p1', 'q1', expect.objectContaining({ type: 'TextAnswer', concurrencyToken: 'qt1', packageConcurrencyToken: 'pt1' }))); });
  it('zachowuje dane po konflikcie i odświeża je na żądanie', async () => { vi.mocked(adminContentApi.updateQuestion).mockRejectedValue(new AdminContentApiError(409, 'Konflikt')); renderPage('/admin/content/packages/p1/questions/q1'); await screen.findByDisplayValue('fun_question'); await userEvent.clear(screen.getByLabelText('Tekst PL')); await userEvent.type(screen.getByLabelText('Tekst PL'), 'Moje dane'); await userEvent.click(screen.getByRole('button', { name: 'Zapisz' })); expect(await screen.findByRole('alert')).toHaveTextContent('zmienione w innej sesji'); expect(screen.getByLabelText('Tekst PL')).toHaveValue('Moje dane'); await userEvent.click(screen.getByRole('button', { name: 'Pozostań przy wpisanych zmianach' })); expect(screen.getByLabelText('Tekst PL')).toHaveValue('Moje dane'); });
  it('ostrzeżenie niezapisanych zmian pozwala zostać albo opuścić formularz', async () => { renderPage(); await screen.findByText('Nowe pytanie'); await userEvent.type(screen.getByLabelText('Key'), 'dirty_question'); await userEvent.click(screen.getByRole('button', { name: 'Anuluj' })); const dialog = screen.getByRole('dialog'); expect(dialog).toHaveFocus(); await userEvent.click(within(dialog).getByRole('button', { name: 'Zostań' })); expect(screen.getByText('Nowe pytanie')).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Anuluj' })); await userEvent.click(screen.getByRole('button', { name: 'Opuść bez zapisywania' })); expect(await screen.findByText('Lista')).toBeInTheDocument(); });
  it.each(['Published', 'Archived'] as const)('wersja %s jest read-only', async status => { vi.mocked(adminContentApi.getPackage).mockResolvedValue({ ...pkg, status }); vi.mocked(adminContentApi.getQuestion).mockResolvedValue({ question, packageConcurrencyToken: 'pt1', packageStatus: status }); renderPage('/admin/content/packages/p1/questions/q1'); await screen.findByDisplayValue('fun_question'); expect(screen.getByText(/tylko do odczytu/)).toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Zapisz' })).not.toBeInTheDocument(); expect(screen.getByLabelText('Key')).toHaveAttribute('readonly'); });
});
