import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { AdminContentApiError, adminContentApi, type Category, type ContentPackage, type Question } from '../../api/adminContentApi';
import { QuestionListPage } from './QuestionListPage';

vi.mock('../../api/adminContentApi', async original => { const actual = await original<typeof import('../../api/adminContentApi')>(); return { ...actual, adminContentApi: { listQuestions: vi.fn(), getPackage: vi.fn(), listCategories: vi.fn(), updateQuestion: vi.fn(), duplicateQuestion: vi.fn(), deleteQuestion: vi.fn(), reorderQuestions: vi.fn() } }; });
const category: Category = { id: 'c1', packageId: 'p1', key: 'fun', namePl: 'Zabawne', nameEn: 'Funny', descriptionPl: '', descriptionEn: '', isActive: true, sortOrder: 0, questionCount: 2, concurrencyToken: 'cat-token' };
const secondCategory: Category = { ...category, id: 'c2', key: 'other', namePl: 'Inne' };
const question: Question = { id: 'q1', packageId: 'p1', categoryId: 'c1', categoryKey: 'fun', categoryNamePl: 'Zabawne', key: 'hello', questionType: 'TextAnswer', type: 'TextAnswer', textPl: 'Jak się masz?', textEn: 'How are you?', isEnabled: true, isActive: true, minimumPlayers: 3, sortOrder: 0, createdAtUtc: '2026-01-01T10:00:00Z', updatedAtUtc: '2026-01-02T10:00:00Z', concurrencyToken: 'q-token', validationErrors: [] };
const pkg = (status: ContentPackage['status'] = 'Draft'): ContentPackage => ({ id: 'p1', logicalPackageId: 'l1', version: 1, key: 'pkg', namePl: 'Pakiet', nameEn: 'Package', status, isActive: true, categoryCount: 1, questionCount: 2, concurrencyToken: 'pt1' });
const page = (items: Question[] = [question], overrides = {}) => ({ items, page: 1, pageSize: 25, totalItems: items.length, totalPages: items.length ? 1 : 0, packageConcurrencyToken: 'pt1', ...overrides });
const renderPage = (entry = '/admin/content/packages/p1/questions') => render(<MemoryRouter initialEntries={[entry]}><Routes><Route path="/admin/content/packages/:packageVersionId/questions" element={<QuestionListPage />} /></Routes></MemoryRouter>);

describe('QuestionListPage', () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(adminContentApi.listQuestions).mockResolvedValue(page()); vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [category], packageConcurrencyToken: 'pt1' }); vi.mocked(adminContentApi.getPackage).mockResolvedValue(pkg()); });
  it('pokazuje loading i kompletny wiersz pytania', async () => { renderPage(); expect(screen.getByText('Wczytywanie pytań…')).toBeInTheDocument(); expect(await screen.findByText('Jak się masz?')).toBeInTheDocument(); expect(screen.getByRole('columnheader', { name: 'Kategoria' })).toBeInTheDocument(); expect(within(screen.getByRole('row', { name: /Jak się masz/ })).getByText('Aktywne')).toBeInTheDocument(); });
  it('pokazuje pusty pakiet oraz pusty wynik filtrów', async () => { vi.mocked(adminContentApi.listQuestions).mockResolvedValueOnce(page([])).mockResolvedValueOnce(page([], { totalItems: 0 })); renderPage(); expect(await screen.findByText('Ten pakiet nie zawiera jeszcze pytań.')).toBeInTheDocument(); renderPage('/admin/content/packages/p1/questions?search=nic'); expect(await screen.findByText('Brak pytań spełniających wybrane kryteria.')).toBeInTheDocument(); });
  it('odtwarza filtry z URL i wysyła je do API', async () => { renderPage('/admin/content/packages/p1/questions?search=hello&categoryId=c1&questionType=TextAnswer&isEnabled=true&page=2&pageSize=10&sort=keyAsc'); await screen.findByText('Jak się masz?'); expect(adminContentApi.listQuestions).toHaveBeenCalledWith('p1', expect.objectContaining({ search: 'hello', categoryId: 'c1', questionType: 'TextAnswer', isEnabled: true, page: 2, pageSize: 10, sort: 'keyAsc' })); });
  it('szuka po jawnym submit i resetuje stronę', async () => { renderPage('/admin/content/packages/p1/questions?page=2'); await screen.findByText('Jak się masz?'); await userEvent.type(screen.getByLabelText('Wyszukaj'), 'nowe'); await userEvent.click(screen.getByRole('button', { name: 'Szukaj' })); await waitFor(() => expect(adminContentApi.listQuestions).toHaveBeenLastCalledWith('p1', expect.objectContaining({ search: 'nowe', page: 1 }))); });
  it('czyści filtry', async () => { renderPage('/admin/content/packages/p1/questions?search=x&categoryId=c1&missingTranslation=true'); await screen.findByText('Jak się masz?'); await userEvent.click(screen.getByRole('button', { name: 'Wyczyść filtry' })); await waitFor(() => expect(adminContentApi.listQuestions).toHaveBeenLastCalledWith('p1', expect.objectContaining({ search: undefined, categoryId: undefined, missingTranslation: undefined, page: 1 }))); });
  it('zachowuje formularz i kategorię po wyczyszczeniu wyszukiwania oraz ignoruje spóźniony request', async () => {
    let resolveSearch!: (value: ReturnType<typeof page>) => void;
    vi.mocked(adminContentApi.listCategories).mockResolvedValue({ items: [category, secondCategory], packageConcurrencyToken: 'pt1' });
    vi.mocked(adminContentApi.listQuestions).mockImplementationOnce(() => Promise.resolve(page())).mockImplementationOnce(() => new Promise(resolve => { resolveSearch = resolve; })).mockResolvedValueOnce(page([{ ...question, id: 'q2', categoryId: 'c2', categoryNamePl: 'Inne', textPl: 'Nowa kategoria' }]));
    renderPage('/admin/content/packages/p1/questions?search=tekst&categoryId=c1');
    await screen.findByText('Jak się masz?');
    const search = screen.getByLabelText('Wyszukaj');
    await userEvent.clear(search); await userEvent.click(screen.getByRole('button', { name: 'Szukaj' }));
    expect(screen.getByLabelText('Kategoria')).toHaveValue('c1');
    await userEvent.selectOptions(screen.getByLabelText('Kategoria'), 'c2');
    await screen.findByText('Nowa kategoria');
    resolveSearch(page([question]));
    expect(await screen.findByText('Nowa kategoria')).toBeInTheDocument();
    expect(adminContentApi.listQuestions).toHaveBeenCalledTimes(3);
    expect(adminContentApi.listQuestions).toHaveBeenLastCalledWith('p1', expect.objectContaining({ search: undefined, categoryId: 'c2', page: 1 }));
  });
  it('pokazuje błąd API i retry zachowuje aktywny filtr', async () => { vi.mocked(adminContentApi.listQuestions).mockRejectedValueOnce(new Error('Sieć')).mockResolvedValueOnce(page()); renderPage('/admin/content/packages/p1/questions?search=hello'); expect(await screen.findByRole('alert')).toHaveTextContent('Sieć'); await userEvent.click(screen.getByRole('button', { name: 'Odśwież listę' })); await screen.findByText('Jak się masz?'); expect(adminContentApi.listQuestions).toHaveBeenLastCalledWith('p1', expect.objectContaining({ search: 'hello' })); });
  it('paginacja używa następnej strony i respektuje granice', async () => { vi.mocked(adminContentApi.listQuestions).mockResolvedValue(page([question], { page: 1, totalItems: 2, totalPages: 2 })); renderPage(); await screen.findByText('Jak się masz?'); expect(screen.getByRole('button', { name: 'Poprzednia' })).toBeDisabled(); await userEvent.click(screen.getByRole('button', { name: 'Następna' })); await waitFor(() => expect(adminContentApi.listQuestions).toHaveBeenLastCalledWith('p1', expect.objectContaining({ page: 2 }))); });
  it('wyłącza pytanie prawdziwym PATCH i zachowuje tokeny', async () => { vi.mocked(adminContentApi.updateQuestion).mockResolvedValue({ question: { ...question, isActive: false, isEnabled: false, concurrencyToken: 'q2' }, packageConcurrencyToken: 'pt2' }); renderPage(); await screen.findByText('Jak się masz?'); await userEvent.click(screen.getByRole('button', { name: 'Wyłącz' })); await waitFor(() => expect(adminContentApi.updateQuestion).toHaveBeenCalledWith('p1', 'q1', { isActive: false, concurrencyToken: 'q-token', packageConcurrencyToken: 'pt1' })); expect(within(screen.getByRole('row', { name: /Jak się masz/ })).getByText('Wyłączone')).toBeInTheDocument(); });
  it('pokazuje konflikt operacji i umożliwia odświeżenie', async () => { vi.mocked(adminContentApi.duplicateQuestion).mockRejectedValue(new AdminContentApiError(409, 'stare')); renderPage(); await screen.findByText('Jak się masz?'); await userEvent.click(screen.getByRole('button', { name: 'Duplikuj' })); expect(await screen.findByRole('alert')).toHaveTextContent('To pytanie zostało zmienione'); });
  it('otwiera modal usuwania, zachowuje go po błędzie i usuwa po sukcesie', async () => { vi.mocked(adminContentApi.deleteQuestion).mockRejectedValueOnce(new Error('Nie można')).mockResolvedValueOnce({ success: true, packageConcurrencyToken: 'pt2' }); renderPage(); await screen.findByText('Jak się masz?'); await userEvent.click(screen.getByRole('button', { name: 'Usuń' })); const dialog = screen.getByRole('dialog'); expect(dialog).toHaveFocus(); await userEvent.click(within(dialog).getByRole('button', { name: 'Usuń' })); expect(await screen.findByRole('alert')).toHaveTextContent('Nie można'); expect(screen.getByRole('dialog')).toBeInTheDocument(); await userEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Usuń' })); await waitFor(() => expect(screen.queryByText('Jak się masz?')).not.toBeInTheDocument()); });
  it('Published pozostawia filtry, ale ukrywa mutacje i tworzenie', async () => { vi.mocked(adminContentApi.getPackage).mockResolvedValue(pkg('Published')); renderPage(); await screen.findByText('Jak się masz?'); expect(screen.getByText(/tylko do odczytu/)).toBeInTheDocument(); expect(screen.getByLabelText('Wyszukaj')).toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Wyłącz' })).not.toBeInTheDocument(); expect(screen.queryByText('Dodaj pytanie')).not.toBeInTheDocument(); });
});
