export const translations = {
  pl: {
    title: 'PartyGame', roomCode: 'Kod pokoju', nickname: 'Twój nick', join: 'Dołącz do gry', joining: 'Dołączanie…',
    joined: 'Dołączono do gry', room: 'Pokój', player: 'Gracz', connection: 'Połączenie', waiting: 'Oczekiwanie na pozostałych graczy…',
    connecting: 'Łączenie', connected: 'Połączono', reconnecting: 'Ponowne łączenie', disconnected: 'Rozłączono',
    roomRequired: 'Wpisz kod pokoju.', nicknameRequired: 'Wpisz nick.', roomLength: 'Kod pokoju ma 4 znaki.', nicknameLength: 'Nick musi mieć od 2 do 20 znaków.',
    roomNotFound: 'Nie znaleziono pokoju.', roomStarted: 'Do tego pokoju nie można już dołączyć.', invalid: 'Dane są nieprawidłowe.', network: 'Brak połączenia z serwerem. Spróbuj ponownie.', server: 'Serwer jest chwilowo niedostępny. Spróbuj ponownie.', cancel: 'Anuluj',
    players: 'Gracze', configurationError: 'Nie można uruchomić PartyGame. Sprawdź konfigurację serwera.', lobby: 'Lobby', ready: 'Gotowy', notReady: 'Nie jestem gotowy', waitingStatus: 'Oczekuje', profile: 'Profil', choosePhoto: 'Wybierz zdjęcie', uploadPhoto: 'Zapisz zdjęcie', uploading: 'Wysyłanie zdjęcia…', uploadFailed: 'Nie udało się wysłać zdjęcia. Spróbuj ponownie.', unsupportedPhoto: 'Wybierz plik graficzny.', photoTooLarge: 'Zdjęcie jest zbyt duże.', photoInvalid: 'Wybierz prawidłowy plik graficzny.', photoProcessing: 'Nie udało się przygotować zdjęcia.', photoRequired: 'Dodaj zdjęcie, aby oznaczyć gotowość.', sessionExpired: 'Sesja wygasła. Dołącz ponownie do pokoju.', gameStarted: 'Gra wystartowała', gameStartedHint: 'Obsługa pytań w przeglądarce będzie dostępna w kolejnym etapie.', offline: 'Brak połączenia', reconnectingHint: 'Przywracanie połączenia…', connectedStatus: 'Połączono', retry: 'Spróbuj ponownie', avatarOf: 'Avatar gracza', you: 'Ty', question: 'Pytanie', choosePlayer: 'Wybierz gracza', submitAnswer: 'Wyślij odpowiedź', answerSubmitted: 'Odpowiedź wysłana', waitingForOthers: 'Oczekiwanie na pozostałych…', vote: 'Głosowanie', submitVote: 'Oddaj głos', voteSubmitted: 'Głos oddany', timeRemaining: 'Pozostały czas', submissionFailed: 'Nie udało się wysłać odpowiedzi.', voteFailed: 'Nie udało się oddać głosu.', unsupportedQuestionType: 'Ten typ pytania nie jest jeszcze obsługiwany.', unsupportedQuestionHint: 'Nie wysyłaj odpowiedzi — poczekaj na kolejne pytanie.', yourAnswer: 'Twoja odpowiedź', submitting: 'Wysyłanie…', timerWaiting: 'czekamy na serwer', stageWaiting: 'Czekamy na zmianę etapu.', gameLoading: 'Ładowanie gry…', notEligibleToVote: 'Nie głosujesz w tym pytaniu.', takePhoto: 'Zrób lub wybierz zdjęcie', changePhoto: 'Wybierz inne zdjęcie', photoPreview: 'Podgląd zdjęcia', processingPhoto: 'Przygotowywanie zdjęcia…', uploadingPhoto: 'Wysyłanie zdjęcia…', submitPhoto: 'Wyślij zdjęcie', photoSubmitted: 'Zdjęcie wysłane', photoUploadFailed: 'Nie udało się wysłać zdjęcia.', drawing: 'Rysunek', drawingCanvas: 'Obszar rysowania', clearDrawing: 'Wyczyść rysunek', clearDrawingConfirm: 'Na pewno wyczyścić rysunek?', undoDrawing: 'Cofnij ruch', submitDrawing: 'Wyślij rysunek', drawingSubmitted: 'Rysunek wysłany', drawingEmpty: 'Najpierw narysuj odpowiedź.', drawingSubmitFailed: 'Nie udało się wysłać rysunku.', mediaLoading: 'Ładowanie mediów…', mediaUnavailable: 'Medium jest niedostępne.', resultsTitle: 'Wyniki', textResults: 'Odpowiedzi tekstowe', photoResults: 'Wyniki zdjęć', drawingResults: 'Wyniki rysunków', roundSummaryTitle: 'Podsumowanie rundy', gameCompleted: 'Gra zakończona', ranking: 'Ranking', finalRanking: 'Końcowy ranking', place: 'Miejsce', points: 'pkt', votes: 'głosów', winner: 'Zwycięzca', waitingForNextRound: 'Czekamy na kolejną rundę…', rankingUnavailable: 'Ranking jest jeszcze niedostępny.', resultsUnavailable: 'Wyniki są jeszcze niedostępne.',
  },
  en: {
    title: 'PartyGame', roomCode: 'Room code', nickname: 'Your nickname', join: 'Join game', joining: 'Joining…',
    joined: 'Joined the game', room: 'Room', player: 'Player', connection: 'Connection', waiting: 'Waiting for other players…',
    connecting: 'Connecting', connected: 'Connected', reconnecting: 'Reconnecting', disconnected: 'Disconnected',
    roomRequired: 'Enter a room code.', nicknameRequired: 'Enter your nickname.', roomLength: 'Room code has 4 characters.', nicknameLength: 'Nickname must have 2 to 20 characters.',
    roomNotFound: 'Room not found.', roomStarted: 'This room can no longer be joined.', invalid: 'The provided details are invalid.', network: 'Cannot reach the server. Please try again.', server: 'The server is temporarily unavailable. Please try again.', cancel: 'Cancel',
    players: 'Players', configurationError: 'PartyGame could not start. Check the server configuration.', lobby: 'Lobby', ready: 'Ready', notReady: 'Not ready', waitingStatus: 'Waiting', profile: 'Profile', choosePhoto: 'Choose photo', uploadPhoto: 'Save photo', uploading: 'Uploading photo…', uploadFailed: 'Photo upload failed. Please try again.', unsupportedPhoto: 'Choose an image file.', photoTooLarge: 'The photo is too large.', photoInvalid: 'Choose a valid image file.', photoProcessing: 'The photo could not be prepared.', photoRequired: 'Add a photo before marking yourself ready.', sessionExpired: 'Your session expired. Join the room again.', gameStarted: 'Game started', gameStartedHint: 'Questions in the browser will be available in a future stage.', offline: 'Offline', reconnectingHint: 'Restoring connection…', connectedStatus: 'Connected', retry: 'Try again', avatarOf: 'Player avatar', you: 'You', question: 'Question', choosePlayer: 'Choose a player', submitAnswer: 'Submit answer', answerSubmitted: 'Answer submitted', waitingForOthers: 'Waiting for other players…', vote: 'Vote', submitVote: 'Submit vote', voteSubmitted: 'Vote submitted', timeRemaining: 'Time remaining', submissionFailed: 'Could not submit your answer.', voteFailed: 'Could not submit your vote.', unsupportedQuestionType: 'This question type is not supported yet.', unsupportedQuestionHint: 'Do not submit an answer — wait for the next question.', yourAnswer: 'Your answer', submitting: 'Submitting…', timerWaiting: 'waiting for server', stageWaiting: 'Waiting for the next stage.', gameLoading: 'Loading game…', notEligibleToVote: 'You are not voting in this question.', takePhoto: 'Take or choose a photo', changePhoto: 'Choose another photo', photoPreview: 'Photo preview', processingPhoto: 'Preparing photo…', uploadingPhoto: 'Uploading photo…', submitPhoto: 'Submit photo', photoSubmitted: 'Photo submitted', photoUploadFailed: 'Could not upload the photo.', drawing: 'Drawing', drawingCanvas: 'Drawing area', clearDrawing: 'Clear drawing', clearDrawingConfirm: 'Clear this drawing?', undoDrawing: 'Undo stroke', submitDrawing: 'Submit drawing', drawingSubmitted: 'Drawing submitted', drawingEmpty: 'Draw an answer first.', drawingSubmitFailed: 'Could not submit the drawing.', mediaLoading: 'Loading media…', mediaUnavailable: 'Media unavailable.', resultsTitle: 'Results', textResults: 'Text answers', photoResults: 'Photo results', drawingResults: 'Drawing results', roundSummaryTitle: 'Round summary', gameCompleted: 'Game completed', ranking: 'Ranking', finalRanking: 'Final ranking', place: 'Place', points: 'pts', votes: 'votes cast', winner: 'Winner', waitingForNextRound: 'Waiting for the next round…', rankingUnavailable: 'Ranking is not available yet.', resultsUnavailable: 'Results are not available yet.',
  },
};

export type Locale = keyof typeof translations;
export type TranslationKey = keyof typeof translations.pl;

export function preferredLocale(): Locale {
  return 'pl';
}
