#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/data-lifecycle-common.sh"
BACKUP="${1:-}"
[[ -n "$BACKUP" && $# -eq 1 ]] || data_die "usage: verify-backup.sh BACKUP_DIRECTORY"
data_require_absolute backup "$BACKUP"
data_validate_backup_layout "$BACKUP"
data_verify_checksums "$BACKUP" >/dev/null || data_die "checksum mismatch" "$DATA_EXIT_CHECKSUM"
data_sqlite_integrity "$BACKUP/database/partygame.db" || data_die "SQLite integrity_check failed" "$DATA_EXIT_SQLITE"
manifest="$BACKUP/backup-manifest.json"
schema="$(data_schema_version "$BACKUP/database/partygame.db")"; expected="$(node -e 'const m=require(process.argv[1]); if (typeof m.databaseSchemaVersion !== "string" || !m.databaseSchemaVersion) process.exit(1); process.stdout.write(m.databaseSchemaVersion)' "$manifest")"
[[ -n "$schema" && "$schema" == "$expected" ]] || data_die "unsupported database schema version" "$DATA_EXIT_SCHEMA"
expected_count="$(node -e 'const m=require(process.argv[1]); if (!Number.isSafeInteger(m.mediaFileCount) || m.mediaFileCount < 0) process.exit(1); process.stdout.write(String(m.mediaFileCount))' "$manifest")"; actual_count="$(find "$BACKUP/media" -type f -not -type l | wc -l | tr -d ' ')"
[[ "$expected_count" == "$actual_count" ]] || data_die "media file count differs from manifest" "$DATA_EXIT_INCOMPLETE"
expected_db_size="$(node -e 'const m=require(process.argv[1]); if (!Number.isSafeInteger(m.databaseSize) || m.databaseSize < 0) process.exit(1); process.stdout.write(String(m.databaseSize))' "$manifest")"; [[ "$expected_db_size" == "$(data_size "$BACKUP/database/partygame.db")" ]] || data_die "database size differs from manifest" "$DATA_EXIT_INCOMPLETE"
expected_media_size="$(node -e 'const m=require(process.argv[1]); if (!Number.isSafeInteger(m.mediaTotalSize) || m.mediaTotalSize < 0) process.exit(1); process.stdout.write(String(m.mediaTotalSize))' "$manifest")"; [[ "$expected_media_size" == "$(data_tree_size "$BACKUP/media")" ]] || data_die "media size differs from manifest" "$DATA_EXIT_INCOMPLETE"
data_validate_media_consistency "$BACKUP"
echo "PartyGame backup verification PASS: $BACKUP"
